/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.nhanvien.quanlynhacungcap;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.util.Arrays;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import vn.edu.iuh.fit.iuhpharmacitymanagement.common.TableDesign;

/**
 *
 * @author PhamTra
 */
public class GD_QuanLyNhaCungCap extends javax.swing.JPanel {

    private TableDesign tableDesign;

    public GD_QuanLyNhaCungCap() {
        initComponents();
        setUIManager();
        fillTable();
    }

    private void setUIManager() {
        // Placeholder cho search
        txtSearchSupplier.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tìm kiếm theo tên, email, số điện thoại");

        // Placeholder cho Add form
        txtSupNameAdd.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập tên nhà cung cấp");
        txtSupPhoneAdd.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập số điện thoại (10 chữ số)");
        txtSupAddressAdd.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập địa chỉ");
        txtSupEmailAdd.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập email");
        txtSupTaxCodeAdd.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mã số thuế (10 hoặc 13 ký tự)");

        // Placeholder cho Edit form
        txtSupNameEdit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập tên nhà cung cấp");
        txtSupPhoneEdit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập số điện thoại (10 chữ số)");
        txtSupAddressEdit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập địa chỉ");
        txtSupEmailEdit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập email");
        txtSupTaxCodeEdit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mã số thuế (10 hoặc 13 ký tự)");

        // Thêm viền cho các TextField
        txtSearchSupplier.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        txtSupNameAdd.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        txtSupPhoneAdd.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        txtSupAddressAdd.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        txtSupEmailAdd.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        txtSupTaxCodeAdd.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        txtSupNameEdit.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        txtSupPhoneEdit.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        txtSupAddressEdit.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        txtSupEmailEdit.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        txtSupTaxCodeEdit.putClientProperty(FlatClientProperties.STYLE, "arc:10");

        UIManager.put("Button.arc", 10);
    }

    private void fillTable() {
        String[] headers = {"Mã NCC", "Tên nhà cung cấp", "Địa chỉ", "Số điện thoại", "Email", "Mã số thuế"};
        List<Integer> tableWidths = Arrays.asList(100, 250, 200, 120, 200, 120);
        tableDesign = new TableDesign(headers, tableWidths);
        SupplierScroll.setViewportView(tableDesign.getTable());
        SupplierScroll.setBorder(BorderFactory.createEmptyBorder(15, 20, 20, 20));

        // Load sample data
        loadSampleData();
    }

    private void loadSampleData() {
        // Không load data, chỉ để trống
        DefaultTableModel model = tableDesign.getModelTable();
        model.setRowCount(0);
    }

    // Helper method để clear nhiều text field cùng lúc
    public void clearData(JTextField... fields) {
        for (JTextField field : fields) {
            field.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelSupplierAdd = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSupPhoneAdd = new javax.swing.JTextField();
        txtSupNameAdd = new javax.swing.JTextField();
        txtSupAddressAdd = new javax.swing.JTextField();
        txtSupTaxCodeAdd = new javax.swing.JTextField();
        txtSupEmailAdd = new javax.swing.JTextField();
        btnSupplierAdd = new javax.swing.JButton();
        btnSupplierExit = new javax.swing.JButton();
        modelSupplierEdit = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtSupPhoneEdit = new javax.swing.JTextField();
        txtSupNameEdit = new javax.swing.JTextField();
        txtSupAddressEdit = new javax.swing.JTextField();
        txtSupTaxCodeEdit = new javax.swing.JTextField();
        txtSupEmailEdit = new javax.swing.JTextField();
        btnSupplierEdit = new javax.swing.JButton();
        btnSupplierExit2 = new javax.swing.JButton();
        pnAll = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtSearchSupplier = new javax.swing.JTextField();
        btnOpenModalAddSup = new javax.swing.JButton();
        actionPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        SupplierScroll = new javax.swing.JScrollPane();

        modelSupplierAdd.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modelSupplierAdd.setModal(true);
        modelSupplierAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modelSupplierAddMouseClicked(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Tên nhà cung cấp :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("SDT :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Địa chỉ :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Mã số Thuế :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Email :");

        txtSupPhoneAdd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupPhoneAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupPhoneAddActionPerformed(evt);
            }
        });

        txtSupNameAdd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupNameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupNameAddActionPerformed(evt);
            }
        });

        txtSupAddressAdd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupAddressAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupAddressAddActionPerformed(evt);
            }
        });

        txtSupTaxCodeAdd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupTaxCodeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupTaxCodeAddActionPerformed(evt);
            }
        });

        txtSupEmailAdd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupEmailAddActionPerformed(evt);
            }
        });

        btnSupplierAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSupplierAdd.setText("Thêm");
        btnSupplierAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierAddActionPerformed(evt);
            }
        });

        btnSupplierExit.setBackground(new java.awt.Color(92, 107, 192));
        btnSupplierExit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSupplierExit.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplierExit.setText("Thoát");
        btnSupplierExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupAddressAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(txtSupNameAdd))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSupEmailAdd)
                            .addComponent(txtSupPhoneAdd)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 715, Short.MAX_VALUE))
                    .addComponent(txtSupTaxCodeAdd)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSupplierAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSupplierExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupPhoneAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupAddressAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupTaxCodeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupplierAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupplierExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modelSupplierAddLayout = new javax.swing.GroupLayout(modelSupplierAdd.getContentPane());
        modelSupplierAdd.getContentPane().setLayout(modelSupplierAddLayout);
        modelSupplierAddLayout.setHorizontalGroup(
            modelSupplierAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modelSupplierAddLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        modelSupplierAddLayout.setVerticalGroup(
            modelSupplierAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        modelSupplierEdit.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modelSupplierEdit.setModal(true);
        modelSupplierEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                modelSupplierEditKeyReleased(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Tên nhà cung cấp :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("SDT :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setText("Địa chỉ :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setText("Mã số Thuế :");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel21.setText("Email :");

        txtSupPhoneEdit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupPhoneEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupPhoneEditActionPerformed(evt);
            }
        });

        txtSupNameEdit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupNameEditActionPerformed(evt);
            }
        });

        txtSupAddressEdit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupAddressEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupAddressEditActionPerformed(evt);
            }
        });

        txtSupTaxCodeEdit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupTaxCodeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupTaxCodeEditActionPerformed(evt);
            }
        });

        txtSupEmailEdit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupEmailEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupEmailEditActionPerformed(evt);
            }
        });

        btnSupplierEdit.setBackground(new java.awt.Color(78, 94, 186));
        btnSupplierEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSupplierEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplierEdit.setText("Sửa");
        btnSupplierEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierEditActionPerformed(evt);
            }
        });

        btnSupplierExit2.setBackground(new java.awt.Color(236, 82, 113));
        btnSupplierExit2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSupplierExit2.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplierExit2.setText("Thoát");
        btnSupplierExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierExit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSupplierEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSupplierExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSupTaxCodeEdit)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(318, 318, 318))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSupAddressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSupNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupEmailEdit)
                            .addComponent(txtSupPhoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(77, 77, 77))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupPhoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupAddressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSupTaxCodeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSupplierEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSupplierExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))))
        );

        javax.swing.GroupLayout modelSupplierEditLayout = new javax.swing.GroupLayout(modelSupplierEdit.getContentPane());
        modelSupplierEdit.getContentPane().setLayout(modelSupplierEditLayout);
        modelSupplierEditLayout.setHorizontalGroup(
            modelSupplierEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modelSupplierEditLayout.setVerticalGroup(
            modelSupplierEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBackground(new java.awt.Color(204, 204, 0));

        pnAll.setBackground(new java.awt.Color(255, 255, 255));
        pnAll.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(232, 232, 232)));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(590, 100));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 16, 24));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(584, 50));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        txtSearchSupplier.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSearchSupplier.setMinimumSize(new java.awt.Dimension(300, 40));
        txtSearchSupplier.setPreferredSize(new java.awt.Dimension(300, 40));
        txtSearchSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSupplierActionPerformed(evt);
            }
        });
        jPanel6.add(txtSearchSupplier);

        btnOpenModalAddSup.setBackground(new java.awt.Color(115, 165, 71));
        btnOpenModalAddSup.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnOpenModalAddSup.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenModalAddSup.setText("Tìm kiếm");
        btnOpenModalAddSup.setMaximumSize(new java.awt.Dimension(150, 40));
        btnOpenModalAddSup.setMinimumSize(new java.awt.Dimension(150, 40));
        btnOpenModalAddSup.setPreferredSize(new java.awt.Dimension(150, 40));
        btnOpenModalAddSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenModalAddSupActionPerformed(evt);
            }
        });
        jPanel6.add(btnOpenModalAddSup);

        jPanel5.add(jPanel6);

        headerPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        actionPanel.setBackground(new java.awt.Color(255, 255, 255));
        actionPanel.setPreferredSize(new java.awt.Dimension(220, 60));
        actionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 25));

        btnAdd.setBackground(new java.awt.Color(115, 165, 71));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Thêm");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.setPreferredSize(new java.awt.Dimension(95, 40));
        btnAdd.setMinimumSize(new java.awt.Dimension(95, 40));
        btnAdd.setMaximumSize(new java.awt.Dimension(95, 40));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        actionPanel.add(btnAdd);

        btnUpdate.setBackground(new java.awt.Color(255, 193, 7));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Sửa");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setFocusPainted(false);
        btnUpdate.setPreferredSize(new java.awt.Dimension(95, 40));
        btnUpdate.setMinimumSize(new java.awt.Dimension(95, 40));
        btnUpdate.setMaximumSize(new java.awt.Dimension(95, 40));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        actionPanel.add(btnUpdate);

        headerPanel.add(actionPanel, java.awt.BorderLayout.WEST);

        pnAll.add(headerPanel, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        // Thêm tiêu đề "Danh sách thông tin nhà cung cấp"
        javax.swing.JPanel titlePanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 12));
        titlePanel.setBackground(new java.awt.Color(23, 162, 184)); // Màu xanh cyan
        javax.swing.JLabel lblTitle = new javax.swing.JLabel("DANH SÁCH THÔNG TIN NHÀ CUNG CẤP");
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16));
        lblTitle.setForeground(new java.awt.Color(255, 255, 255)); // Chữ màu trắng
        titlePanel.add(lblTitle);
        jPanel4.add(titlePanel, java.awt.BorderLayout.NORTH);

        jPanel4.add(SupplierScroll, java.awt.BorderLayout.CENTER);

        pnAll.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenModalAddSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenModalAddSupActionPerformed
        // TODO: Implement search functionality
    }//GEN-LAST:event_btnOpenModalAddSupActionPerformed

    private void txtSearchSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSupplierActionPerformed

    }//GEN-LAST:event_txtSearchSupplierActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = tableDesign.getTable().getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp cần sửa!", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy thông tin từ bảng
        String maNCC = tableDesign.getTable().getValueAt(selectedRow, 0).toString();
        String tenNCC = tableDesign.getTable().getValueAt(selectedRow, 1).toString();
        String diaChi = tableDesign.getTable().getValueAt(selectedRow, 2).toString();
        String sdt = tableDesign.getTable().getValueAt(selectedRow, 3).toString();
        String email = tableDesign.getTable().getValueAt(selectedRow, 4).toString();
        String maSoThue = tableDesign.getTable().getValueAt(selectedRow, 5).toString();

        // Hiển thị lên modal edit
        supplierIdEdit = maNCC;
        txtSupNameEdit.setText(tenNCC);
        txtSupPhoneEdit.setText(sdt);
        txtSupAddressEdit.setText(diaChi);
        txtSupEmailEdit.setText(email);
        txtSupTaxCodeEdit.setText(maSoThue);

        modelSupplierEdit.setLocationRelativeTo(this);
        modelSupplierEdit.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        modelSupplierAdd.setLocationRelativeTo(this);
        modelSupplierAdd.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void modelSupplierAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modelSupplierAddMouseClicked
        // Đóng modal khi click ra ngoài
        if (evt.getSource() == modelSupplierAdd) {
            modelSupplierAdd.dispose();
        }
    }//GEN-LAST:event_modelSupplierAddMouseClicked

    private void txtSupPhoneEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupPhoneEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupPhoneEditActionPerformed

    private void txtSupNameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupNameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupNameEditActionPerformed

    private void txtSupAddressEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupAddressEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupAddressEditActionPerformed

    private void txtSupTaxCodeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupTaxCodeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupTaxCodeEditActionPerformed

    private void txtSupEmailEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupEmailEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupEmailEditActionPerformed

    private void btnSupplierEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupplierEditActionPerformed

    private void modelSupplierEditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelSupplierEditKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_modelSupplierEditKeyReleased

    private void btnSupplierExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierExit2ActionPerformed
        clearData(txtSupNameEdit, txtSupPhoneEdit, txtSupEmailEdit, txtSupAddressEdit, txtSupTaxCodeEdit);
        modelSupplierEdit.dispose();
    }//GEN-LAST:event_btnSupplierExit2ActionPerformed

    private void btnSupplierExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierExitActionPerformed
        clearData(txtSupNameAdd, txtSupPhoneAdd, txtSupEmailAdd, txtSupAddressAdd, txtSupTaxCodeAdd);
        modelSupplierAdd.dispose();
    }//GEN-LAST:event_btnSupplierExitActionPerformed

    private void btnSupplierAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupplierAddActionPerformed

    private void txtSupEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupEmailAddActionPerformed

    private void txtSupTaxCodeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupTaxCodeAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupTaxCodeAddActionPerformed

    private void txtSupAddressAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupAddressAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupAddressAddActionPerformed

    private void txtSupNameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupNameAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupNameAddActionPerformed

    private void txtSupPhoneAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupPhoneAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupPhoneAddActionPerformed

    private String supplierIdEdit;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SupplierScroll;
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnOpenModalAddSup;
    private javax.swing.JButton btnSupplierAdd;
    private javax.swing.JButton btnSupplierEdit;
    private javax.swing.JButton btnSupplierExit;
    private javax.swing.JButton btnSupplierExit2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JDialog modelSupplierAdd;
    private javax.swing.JDialog modelSupplierEdit;
    private javax.swing.JPanel pnAll;
    private javax.swing.JTextField txtSearchSupplier;
    private javax.swing.JTextField txtSupAddressAdd;
    private javax.swing.JTextField txtSupAddressEdit;
    private javax.swing.JTextField txtSupEmailAdd;
    private javax.swing.JTextField txtSupEmailEdit;
    private javax.swing.JTextField txtSupNameAdd;
    private javax.swing.JTextField txtSupNameEdit;
    private javax.swing.JTextField txtSupPhoneAdd;
    private javax.swing.JTextField txtSupPhoneEdit;
    private javax.swing.JTextField txtSupTaxCodeAdd;
    private javax.swing.JTextField txtSupTaxCodeEdit;
    // End of variables declaration//GEN-END:variables

}
