-- Xem cau truc bang dontrahang
USE IUHPharmacityManagement;

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dontrahang'
ORDER BY ORDINAL_POSITION;

