/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.loading;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.login.LoginFrame;

/**
 *
 * @author User
 */
public class SplashScreen extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SplashScreen.class.getName());
    private Timer timer;

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();

        BackgroundPanel.setComponentZOrder(ProgressBar, 0); // ProgressBar ở lớp trên cùng
        BackgroundPanel.setComponentZOrder(lblLoading, 1);
        BackgroundPanel.setComponentZOrder(ProgressBar, 2);
        BackgroundPanel.setComponentZOrder(IUHLogo, 3);
        BackgroundPanel.setComponentZOrder(BackgroundImg, 3);

        setLocationRelativeTo(null);
        setResizable(false);
        IUHLogo.setSize(424, 300);

        new Thread(() -> {
            setImageToLabel(BackgroundImg, "/img/LoadingImage.png");
            setImageToLabel(IUHLogo, "/img/IUH.png");
        }).start();

        timer = new Timer(100, new ActionListener() {
            int i = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                i++;
                setProgress(i);
                if (i == 5) {
                    lblLoading.setText("Đang khởi tạo hệ thống...");
                }
                if (i == 15) {
                    lblLoading.setText("Đang tải giao diện người dùng...");
                }
                if (i == 30) {
                    lblLoading.setText("Đang kết nối cơ sở dữ liệu...");
                }
                if (i == 50) {
                    lblLoading.setText("Đang khởi động các module chức năng...");
                }
                if (i == 70) {
                    lblLoading.setText("Đang kiểm tra cấu hình...");
                }
                if (i == 90) {
                    lblLoading.setText("Chuẩn bị hoàn tất...");
                }
                if (i >= 100) {
                    lblLoading.setText("Hoàn tất! Đang vào hệ thống...");
                    timer.stop(); 
                    dispose(); // Đóng splash 
                    new LoginFrame().setVisible(true);
                }

            }
        });
        timer.start();
    }

    public void setProgress(int value) {
        //quyền truy cập private ProgressBar để hiện số tiến trình
        this.ProgressBar.setValue(value);
    }

    private void setImageToLabel(javax.swing.JLabel label, String imagePath) {
        try {
            java.net.URL imgURL = getClass().getResource(imagePath);
            System.out.println("Đường dẫn ảnh: " + imgURL);

            if (imgURL != null) {
                ImageIcon originalIcon = new ImageIcon(imgURL);
                Image scaledImage = originalIcon.getImage().getScaledInstance(
                        label.getWidth(),
                        label.getHeight(),
                        Image.SCALE_SMOOTH
                );
                label.setIcon(new ImageIcon(scaledImage));
            } else {
                logger.warning("Không tìm thấy ảnh ở đường dẫn: " + imagePath);
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Lỗi khi load hình ảnh", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        BackgroundImg = new javax.swing.JLabel();
        IUHLogo = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        lblLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setMinimumSize(new java.awt.Dimension(1200, 500));
        BackgroundPanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundImg.setText("BackgroundImage");
        BackgroundImg.setPreferredSize(new java.awt.Dimension(1200, 600));
        BackgroundPanel.add(BackgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -2, 1200, 600));

        IUHLogo.setText("IUHLogo");
        IUHLogo.setMaximumSize(new java.awt.Dimension(424, 300));
        IUHLogo.setMinimumSize(new java.awt.Dimension(424, 300));
        IUHLogo.setPreferredSize(new java.awt.Dimension(424, 300));
        BackgroundPanel.add(IUHLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 140));

        ProgressBar.setStringPainted(true);
        BackgroundPanel.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 576, 1190, -1));

        lblLoading.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoading.setText("Loading...");
        BackgroundPanel.add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImg;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel IUHLogo;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel lblLoading;
    // End of variables declaration//GEN-END:variables
}
