/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.quanly.quanlyxuathuy;

import vn.edu.iuh.fit.iuhpharmacitymanagement.bus.HangHongBUS;
import vn.edu.iuh.fit.iuhpharmacitymanagement.bus.ChiTietHangHongBUS;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Cursor;
import java.util.Arrays;
import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import vn.edu.iuh.fit.iuhpharmacitymanagement.common.TableDesign;
import vn.edu.iuh.fit.iuhpharmacitymanagement.entity.*;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.ImageIcon;
import raven.toast.Notifications;
import vn.edu.iuh.fit.iuhpharmacitymanagement.dao.HangHongDAO;
import vn.edu.iuh.fit.iuhpharmacitymanagement.gui.theme.ButtonStyles;
import vn.edu.iuh.fit.iuhpharmacitymanagement.gui.theme.FontStyles;

/**
 *
 * @author PhamTra
 */
public class GD_QuanLyXuatHuy extends javax.swing.JPanel {

    private final HangHongBUS hangHongBUS;
    private final ChiTietHangHongBUS chiTietHangHongBUS;
    private TableDesign tableDesign;

    public GD_QuanLyXuatHuy() {
        hangHongBUS = new HangHongBUS();
        chiTietHangHongBUS = new ChiTietHangHongBUS();
        initComponents();
        setUIManager();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modalPurchaseOrderDetail = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        scrollTableDetail = new javax.swing.JScrollPane();
        pnAll = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtEmp = new javax.swing.JTextField();
        jDateTo = new com.toedter.calendar.JDateChooser();
        jDateFrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtOrder = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();

        modalPurchaseOrderDetail.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modalPurchaseOrderDetail.setTitle("Chi tiết phiếu xuất hủy");
        modalPurchaseOrderDetail.setMinimumSize(new java.awt.Dimension(960, 512));
        modalPurchaseOrderDetail.setModal(true);
        modalPurchaseOrderDetail.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(scrollTableDetail);

        javax.swing.GroupLayout modalPurchaseOrderDetailLayout = new javax.swing.GroupLayout(modalPurchaseOrderDetail.getContentPane());
        modalPurchaseOrderDetail.getContentPane().setLayout(modalPurchaseOrderDetailLayout);
        modalPurchaseOrderDetailLayout.setHorizontalGroup(
            modalPurchaseOrderDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modalPurchaseOrderDetailLayout.setVerticalGroup(
            modalPurchaseOrderDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 204, 0));
        setMinimumSize(new java.awt.Dimension(1226, 278));
        setPreferredSize(new java.awt.Dimension(1226, 278));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        pnAll.setBackground(new java.awt.Color(255, 255, 255));
        pnAll.setPreferredSize(new java.awt.Dimension(1226, 278));
        pnAll.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(232, 232, 232)));
        headerPanel.setMinimumSize(new java.awt.Dimension(1190, 104));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(590, 100));

        btnSearch.setBackground(new java.awt.Color(115, 165, 71));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("TÌM KIẾM");
        btnSearch.setMaximumSize(new java.awt.Dimension(150, 40));
        btnSearch.setMinimumSize(new java.awt.Dimension(150, 40));
        btnSearch.setPreferredSize(new java.awt.Dimension(150, 40));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmp.setMinimumSize(new java.awt.Dimension(350, 40));
        txtEmp.setPreferredSize(new java.awt.Dimension(350, 40));

        jDateTo.setBackground(new java.awt.Color(255, 255, 255));
        jDateTo.setDateFormatString("dd/MM/yyyy");
        jDateTo.setFocusable(false);
        jDateTo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jDateTo.setPreferredSize(new java.awt.Dimension(100, 22));

        jDateFrom.setBackground(new java.awt.Color(255, 255, 255));
        jDateFrom.setDateFormatString("dd/MM/yyyy");
        jDateFrom.setFocusable(false);
        jDateFrom.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jDateFrom.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("-->");

        txtOrder.setBackground(new java.awt.Color(115, 165, 71));
        txtOrder.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtOrder.setForeground(new java.awt.Color(255, 255, 255));
        txtOrder.setText("XUẤT EXCEL");
        txtOrder.setMaximumSize(new java.awt.Dimension(150, 40));
        txtOrder.setMinimumSize(new java.awt.Dimension(150, 40));
        txtOrder.setPreferredSize(new java.awt.Dimension(150, 40));
        txtOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnView.setText("XEM CHI TIẾT");
        btnView.setBorder(null);
        btnView.setBorderPainted(false);
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.setFocusPainted(false);
        btnView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnView.setPreferredSize(new java.awt.Dimension(130, 40));
        btnView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10)
                .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        pnAll.add(headerPanel, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(1226, 174));
        jPanel4.setPreferredSize(new java.awt.Dimension(1226, 174));
        jPanel4.setLayout(new java.awt.BorderLayout());

        // Thêm tiêu đề "DANH SÁCH THÔNG TIN XUẤT HỦY"
        javax.swing.JPanel titlePanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 12));
        titlePanel.setBackground(new java.awt.Color(23, 162, 184)); // Màu xanh cyan
        javax.swing.JLabel lblTitle = new javax.swing.JLabel("DANH SÁCH THÔNG TIN XUẤT HỦY");
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16));
        lblTitle.setForeground(new java.awt.Color(255, 255, 255)); // Chữ màu trắng
        titlePanel.add(lblTitle);
        jPanel4.add(titlePanel, java.awt.BorderLayout.NORTH);

        jPanel4.add(scrollTable, java.awt.BorderLayout.CENTER);

        pnAll.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(pnAll);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Tạo panel thông tin phiếu xuất hủy cho dialog chi tiết
     */
    private javax.swing.JPanel createHeaderInfoPanel(HangHong hangHong) {
        javax.swing.JPanel headerInfoPanel = new javax.swing.JPanel();
        headerInfoPanel.setBackground(new java.awt.Color(240, 248, 255)); // Alice Blue
        headerInfoPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(23, 162, 184)),
                BorderFactory.createEmptyBorder(15, 20, 15, 20)
        ));
        headerInfoPanel.setLayout(new java.awt.GridLayout(2, 2, 20, 10));

        // Thông tin phiếu
        String maNV = hangHong.getNhanVien() != null ? hangHong.getNhanVien().getMaNhanVien() : "N/A";
        String tenNV = hangHong.getNhanVien() != null ? hangHong.getNhanVien().getTenNhanVien() : "N/A";

        // Tạo các label thông tin
        headerInfoPanel.add(createInfoLabel("Mã phiếu xuất hủy:", hangHong.getMaHangHong()));
        headerInfoPanel.add(createInfoLabel("Ngày xuất hủy:", formatDate(hangHong.getNgayNhap())));
        headerInfoPanel.add(createInfoLabel("Nhân viên:", maNV + " - " + tenNV));
        headerInfoPanel.add(createInfoLabel("Tổng tiền:", formatToVND(hangHong.getThanhTien())));

        return headerInfoPanel;
    }

    /**
     * Tạo label thông tin với title và value
     */
    private javax.swing.JPanel createInfoLabel(String title, String value) {
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        panel.setBackground(new java.awt.Color(240, 248, 255));

        javax.swing.JLabel lblTitle = new javax.swing.JLabel(title);
        lblTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        javax.swing.JLabel lblValue = new javax.swing.JLabel(value);
        lblValue.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));

        panel.add(lblTitle);
        panel.add(lblValue);

        return panel;
    }

    private void setUIManager() {
        txtEmp.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập hoặc quét mã phiếu xuất hủy");
        UIManager.put("Button.arc", 10);
        jDateFrom.setDate(Date.valueOf(LocalDate.now()));
        jDateTo.setDate(Date.valueOf(LocalDate.now()));

        FontStyles.apply(btnView, FontStyles.Type.TEXT_MEDIUM);
        FontStyles.apply(btnSearch, FontStyles.Type.TEXT_MEDIUM);
        FontStyles.apply(txtOrder, FontStyles.Type.TEXT_MEDIUM);

        btnView.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnSearch.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        txtOrder.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        ButtonStyles.apply(btnView, ButtonStyles.Type.PRIMARY);
        ButtonStyles.apply(btnSearch, ButtonStyles.Type.SUCCESS);
        ButtonStyles.apply(txtOrder, ButtonStyles.Type.SUCCESS);

        // Setup barcode scanner cho textfield tìm kiếm
        setupBarcodeScanner();
    }

    private void fillTable() {
        String[] headers = {"Mã phiếu xuất hủy", "Ngày xuất hủy", "Nhân viên", "Tổng tiền"};
        List<Integer> tableWidths = Arrays.asList(250, 250, 350, 250);
        tableDesign = new TableDesign(headers, tableWidths);
        scrollTable.setViewportView(tableDesign.getTable());
        scrollTable.setBorder(BorderFactory.createEmptyBorder(15, 20, 20, 20));
        List<HangHong> hangHongs = hangHongBUS.layTatCaHangHong();
        fillContent(hangHongs);
    }

    private List<HangHong> sortNewToOld(List<HangHong> hangHongs) {
        List<HangHong> hh = new HangHongDAO().findAll();
        hh.sort((a, b) -> {
            String maA = a.getMaHangHong().substring(2); // DDMMYYYYNNNN
            String maB = b.getMaHangHong().substring(2);

            int ngayA = Integer.parseInt(maA.substring(0, 2));
            int thangA = Integer.parseInt(maA.substring(2, 4));
            int namA = Integer.parseInt(maA.substring(4, 8));
            int soCuoiA = Integer.parseInt(maA.substring(8));

            int ngayB = Integer.parseInt(maB.substring(0, 2));
            int thangB = Integer.parseInt(maB.substring(2, 4));
            int namB = Integer.parseInt(maB.substring(4, 8));
            int soCuoiB = Integer.parseInt(maB.substring(8));

            if (namA != namB) {
                return Integer.compare(namA, namB);
            }
            if (thangA != thangB) {
                return Integer.compare(thangA, thangB);
            }
            if (ngayA != ngayB) {
                return Integer.compare(ngayA, ngayB);
            }

            return Integer.compare(soCuoiB, soCuoiA);
        });
        return hh;
    }

    private void fillContent(List<HangHong> hangHongs) {
        tableDesign.getModelTable().setRowCount(0);
        List<HangHong> hh = sortNewToOld(hangHongs);
        for (HangHong hangHong : hh) {
            String tenNV = hangHong.getNhanVien() != null ? hangHong.getNhanVien().getMaNhanVien() : "N/A";

            tableDesign.getModelTable().addRow(new Object[]{
                hangHong.getMaHangHong(),
                formatDate(hangHong.getNgayNhap()),
                tenNV,
                formatToVND(hangHong.getThanhTien())
            });
        }
    }

    private List<HangHong> searchHangHong(LocalDate dateFrom, LocalDate dateTo, String maPhieu) {
        List<HangHong> all = hangHongBUS.layTatCaHangHong();
        List<HangHong> result = new ArrayList<>();

        for (HangHong hh : all) {
            LocalDate ngayNhap = hh.getNgayNhap();

            // Lọc theo ngày
            if (ngayNhap.isBefore(dateFrom) || ngayNhap.isAfter(dateTo)) {
                continue;
            }

            // Lọc theo mã phiếu xuất hủy
            if (!maPhieu.isEmpty()) {
                if (hh.getMaHangHong() == null
                        || !hh.getMaHangHong().toLowerCase().contains(maPhieu.toLowerCase())) {
                    continue;
                }
            }

            result.add(hh);
        }

        return result;
    }

    private String formatDate(LocalDate date) {
        if (date == null) {
            return "N/A";
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return date.format(formatter);
    }

    @SuppressWarnings("deprecation")
    private String formatToVND(double amount) {
        NumberFormat formatter = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
        return formatter.format(amount);
    }

    /**
     * Thiết lập barcode scanner listener cho textfield tìm kiếm mã phiếu xuất
     * hủy Hỗ trợ cả quét barcode (tự động xử lý) và nhập thủ công (xử lý khi
     * nhấn Enter)
     */
    private void setupBarcodeScanner() {
        // Biến để theo dõi trạng thái xử lý (tránh xử lý nhiều lần)
        final java.util.concurrent.atomic.AtomicBoolean isProcessing = new java.util.concurrent.atomic.AtomicBoolean(false);
        final java.util.concurrent.atomic.AtomicBoolean isClearing = new java.util.concurrent.atomic.AtomicBoolean(false);
        final javax.swing.Timer[] barcodeTimer = new javax.swing.Timer[1]; // Mảng để có thể thay đổi trong lambda

        // Theo dõi thời gian giữa các lần gõ để phân biệt quét vs nhập thủ công
        final long[] lastKeyTime = new long[1];
        lastKeyTime[0] = System.currentTimeMillis();
        final int[] keyCount = new int[1];
        keyCount[0] = 0;
        final long[] firstKeyTime = new long[1];
        firstKeyTime[0] = 0;

        // KeyListener để theo dõi tốc độ gõ phím
        txtEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                long currentTime = System.currentTimeMillis();
                long timeSinceLastKey = currentTime - lastKeyTime[0];

                // Ghi nhận thời gian ký tự đầu tiên
                if (firstKeyTime[0] == 0) {
                    firstKeyTime[0] = currentTime;
                }

                // Nếu khoảng cách giữa các lần gõ < 50ms → có thể là quét barcode
                if (timeSinceLastKey < 50) {
                    keyCount[0]++;
                } else if (timeSinceLastKey > 200) {
                    // Nếu khoảng cách > 200ms → rõ ràng là nhập thủ công, reset counter
                    keyCount[0] = 1;
                    firstKeyTime[0] = currentTime;
                } else {
                    // Khoảng cách 50-200ms → có thể là gõ nhanh, tăng counter
                    keyCount[0]++;
                }

                lastKeyTime[0] = currentTime;
            }

            @Override
            public void keyPressed(java.awt.event.KeyEvent e) {
                // Khi nhấn Enter, tự động tìm kiếm (nhập thủ công)
                if (e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    btnSearchActionPerformed(null);
                }
            }
        });

        // DocumentListener để bắt mọi thay đổi text
        txtEmp.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            private void handleTextChange() {
                // Bỏ qua nếu đang clear textfield
                if (isClearing.get()) {
                    return;
                }

                // Hủy timer cũ nếu có
                if (barcodeTimer[0] != null && barcodeTimer[0].isRunning()) {
                    barcodeTimer[0].stop();
                }

                // Tạo timer mới: đợi 200ms không có thay đổi → kiểm tra xem có phải quét không
                barcodeTimer[0] = new javax.swing.Timer(200, evt -> {
                    String scannedText = txtEmp.getText().trim();

                    // Loại bỏ ký tự đặc biệt từ barcode scanner (\r, \n, \t)
                    scannedText = scannedText.replaceAll("[\\r\\n\\t]", "");

                    // Cập nhật lại textfield với giá trị đã làm sạch (nếu cần)
                    if (!scannedText.equals(txtEmp.getText().trim()) && !isClearing.get()) {
                        isClearing.set(true);
                        txtEmp.setText(scannedText);
                        isClearing.set(false);
                    }

                    // Phân biệt quét barcode vs nhập thủ công:
                    // - Quét barcode: nhiều ký tự (>= 5) được nhập rất nhanh (keyCount >= 5 và thời gian tổng < 500ms)
                    // - Nhập thủ công: ít ký tự hoặc gõ chậm → không tự động xử lý, chờ Enter
                    long totalTime = firstKeyTime[0] > 0 ? (System.currentTimeMillis() - firstKeyTime[0]) : 0;
                    boolean isBarcodeScan = scannedText.length() >= 5 && keyCount[0] >= 5 && totalTime < 500;

                    if (!scannedText.isEmpty() && !isProcessing.get() && !isClearing.get() && isBarcodeScan) {
                        isProcessing.set(true);
                        // Tự động tìm kiếm khi quét barcode
                        performSearch(scannedText);
                        isProcessing.set(false);

                        // Clear textfield sau khi xử lý để sẵn sàng quét tiếp
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            javax.swing.Timer clearTimer = new javax.swing.Timer(500, e -> {
                                isClearing.set(true);
                                txtEmp.setText("");
                                isClearing.set(false);
                                keyCount[0] = 0; // Reset counter
                                firstKeyTime[0] = 0; // Reset first key time
                            });
                            clearTimer.setRepeats(false);
                            clearTimer.start();
                        });
                    }

                    // Reset counter sau một khoảng thời gian (nếu không phải quét)
                    if (!isBarcodeScan) {
                        keyCount[0] = 0;
                        firstKeyTime[0] = 0;
                    }
                });
                barcodeTimer[0].setRepeats(false);
                barcodeTimer[0].start();
            }

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                handleTextChange();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                // Khi xóa text, reset counter (người dùng đang chỉnh sửa)
                keyCount[0] = 0;
                firstKeyTime[0] = 0;
                lastKeyTime[0] = System.currentTimeMillis();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                handleTextChange();
            }
        });
    }

    /**
     * Thực hiện tìm kiếm với mã phiếu đã quét/nhập
     */
    private void performSearch(String maPhieu) {
        // Lấy thông tin từ form
        java.util.Date date1 = jDateFrom.getDate();
        java.util.Date date2 = jDateTo.getDate();

        if (date1 == null || date2 == null) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Vui lòng chọn khoảng thời gian!");
            return;
        }

        LocalDate localDateStart = date1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate localDateEnd = date2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        if (localDateStart.isAfter(localDateEnd)) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Ngày bắt đầu phải trước ngày kết thúc!");
            return;
        }

        List<HangHong> hangHongs = searchHangHong(localDateStart, localDateEnd, maPhieu);
        fillContent(hangHongs);

        if (hangHongs.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.INFO, "Không tìm thấy phiếu xuất hủy với mã: " + maPhieu);
        } else {
            Notifications.getInstance().show(Notifications.Type.SUCCESS, "Tìm thấy " + hangHongs.size() + " phiếu xuất hủy!");

            // Tự động chọn dòng đầu tiên nếu có kết quả
            if (hangHongs.size() == 1 && tableDesign != null && tableDesign.getTable() != null) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    tableDesign.getTable().setRowSelectionInterval(0, 0);
                    tableDesign.getTable().scrollRectToVisible(tableDesign.getTable().getCellRect(0, 0, true));
                });
            }
        }
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // Lấy thông tin từ form
        java.util.Date date1 = jDateFrom.getDate();
        java.util.Date date2 = jDateTo.getDate();

        if (date1 == null || date2 == null) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Vui lòng chọn khoảng thời gian!");
            return;
        }

        LocalDate localDateStart = date1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate localDateEnd = date2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        if (localDateStart.isAfter(localDateEnd)) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Ngày bắt đầu phải trước ngày kết thúc!");
            return;
        }

        String maPhieu = txtEmp.getText().trim();
        List<HangHong> hangHongs = searchHangHong(localDateStart, localDateEnd, maPhieu);
        fillContent(hangHongs);

        if (hangHongs.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.INFO, "Không tìm thấy phiếu xuất hủy nào!");
        } else {
            Notifications.getInstance().show(Notifications.Type.SUCCESS, "Tìm thấy " + hangHongs.size() + " phiếu xuất hủy!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderActionPerformed
        boolean success = vn.edu.iuh.fit.iuhpharmacitymanagement.util.XuatFileExcel.xuatExcelVoiDialogVaTieuDe(
                tableDesign.getTable(),
                "DanhSachXuatHuy",
                "Xuất Hủy",
                "DANH SÁCH THÔNG TIN XUẤT HỦY"
        );
        if (success) {
            Notifications.getInstance().show(Notifications.Type.SUCCESS, "Xuất file Excel thành công!");
        } else {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Xuất file Excel thất bại!");
        }
    }//GEN-LAST:event_txtOrderActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        JTable table = tableDesign.getTable();
        int selectedRow = table.getSelectedRow();

        if (selectedRow < 0) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Hãy chọn phiếu xuất hủy cần xem chi tiết!");
            return;
        }

        String maHH = (String) table.getValueAt(selectedRow, 0);

        HangHong hangHong = hangHongBUS.layHangHongTheoMa(maHH);

        if (hangHong == null) {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Không tìm thấy phiếu xuất hủy với mã: " + maHH);
            return;
        }

        List<ChiTietHangHong> chiTietHangHongs = chiTietHangHongBUS.layChiTietTheoHangHong(hangHong);

        if (chiTietHangHongs == null || chiTietHangHongs.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Phiếu xuất hủy không có chi tiết sản phẩm!");
            return;
        }

        // Tạo header panel thông tin phiếu
        javax.swing.JPanel headerInfoPanel = createHeaderInfoPanel(hangHong);

        // Sử dụng Map để cộng dồn các chi tiết CÙNG lô hàng VÀ CÙNG lý do
        // (KHÔNG gộp nếu khác lý do xuất hủy)
        Map<String, ChiTietHangHong> productMap = new HashMap<>();

        for (ChiTietHangHong chiTiet : chiTietHangHongs) {
            String maLoHang = chiTiet.getLoHang() != null ? chiTiet.getLoHang().getMaLoHang() : "N/A";
            String lyDoXuatHuy = chiTiet.getLyDoXuatHuy() != null && !chiTiet.getLyDoXuatHuy().trim().isEmpty()
                    ? chiTiet.getLyDoXuatHuy() : "N/A";

            // Key duy nhất: maLoHang + lyDoXuatHuy
            // → Chỉ gộp khi CÙNG lô hàng VÀ CÙNG lý do
            String productKey = maLoHang + "___" + lyDoXuatHuy;

            if (productMap.containsKey(productKey)) {
                // Nếu chi tiết đã tồn tại trong Map (cùng lô, cùng lý do), cộng dồn số lượng và thành tiền
                ChiTietHangHong existing = productMap.get(productKey);
                try {
                    existing.setSoLuong(existing.getSoLuong() + chiTiet.getSoLuong());
                    existing.setThanhTien(existing.getThanhTien() + chiTiet.getThanhTien());
                } catch (Exception e) {
                    System.err.println("Lỗi khi cộng dồn số lượng: " + e.getMessage());
                }
            } else {
                // Nếu chi tiết chưa tồn tại trong Map (khác lô hoặc khác lý do), thêm mới vào Map
                productMap.put(productKey, chiTiet);
            }
        }

        // Tạo bảng hiển thị chi tiết sản phẩm
        String[] columnNames = {"STT", "Hình ảnh", "Tên sản phẩm", "Lô hàng", "HSD", "Đơn vị", "Số lượng", "Đơn giá", "Thành tiền", "Lý do"};
        javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 1) { // Cột hình ảnh
                    return ImageIcon.class;
                }
                return Object.class;
            }
        };

        // Thêm dữ liệu vào bảng
        int stt = 1;
        for (ChiTietHangHong chiTiet : productMap.values()) {
            if (chiTiet.getLoHang() != null && chiTiet.getLoHang().getSanPham() != null) {
                LoHang loHang = chiTiet.getLoHang();
                SanPham sp = loHang.getSanPham();

                // Load hình ảnh
                ImageIcon imageIcon = null;
                String hinhAnh = sp.getHinhAnh();
                if (hinhAnh != null && !hinhAnh.trim().isEmpty()) {
                    try {
                        java.io.File imageFile = new java.io.File("src/main/resources/img/" + hinhAnh);
                        if (!imageFile.exists()) {
                            imageFile = new java.io.File(hinhAnh);
                        }
                        if (imageFile.exists()) {
                            java.awt.Image img = javax.imageio.ImageIO.read(imageFile);
                            if (img != null) {
                                java.awt.Image scaledImg = img.getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH);
                                imageIcon = new ImageIcon(scaledImg);
                            }
                        }
                    } catch (Exception e) {
                        System.err.println("Lỗi khi load hình ảnh: " + hinhAnh + " - " + e.getMessage());
                    }
                }

                String tenSP = sp.getTenSanPham();
                String maLoHang = loHang.getMaLoHang();
                String hsd = loHang.getHanSuDung() != null ? loHang.getHanSuDung().toString() : "N/A";
                String donVi = sp.getDonViTinh() != null ? sp.getDonViTinh().getTenDonVi() : "N/A";
                int soLuong = chiTiet.getSoLuong();
                String donGia = formatToVND(chiTiet.getDonGia());
                String thanhTien = formatToVND(chiTiet.getThanhTien());
                String lyDo = chiTiet.getLyDoXuatHuy() != null && !chiTiet.getLyDoXuatHuy().trim().isEmpty()
                        ? chiTiet.getLyDoXuatHuy() : "N/A";

                tableModel.addRow(new Object[]{stt++, imageIcon, tenSP, maLoHang, hsd, donVi, soLuong, donGia, thanhTien, lyDo});
            }
        }

        // Tạo JTable
        javax.swing.JTable tableDetail = new javax.swing.JTable(tableModel);
        tableDetail.setRowHeight(70);
        tableDetail.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        tableDetail.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        tableDetail.getTableHeader().setBackground(new java.awt.Color(240, 240, 240));
        tableDetail.setGridColor(new java.awt.Color(220, 220, 220));
        tableDetail.setSelectionBackground(new java.awt.Color(173, 216, 230)); // Light Blue
        tableDetail.setSelectionForeground(new java.awt.Color(0, 0, 0)); // Black text

        // Thiết lập renderer cho cột hình ảnh
        tableDetail.getColumnModel().getColumn(1).setCellRenderer(new vn.edu.iuh.fit.iuhpharmacitymanagement.common.ImageTableCellRenderer());

        // Thiết lập độ rộng cột
        tableDetail.getColumnModel().getColumn(0).setPreferredWidth(50);   // STT
        tableDetail.getColumnModel().getColumn(1).setPreferredWidth(80);   // Hình ảnh
        tableDetail.getColumnModel().getColumn(2).setPreferredWidth(200);  // Tên sản phẩm
        tableDetail.getColumnModel().getColumn(3).setPreferredWidth(100);  // Lô hàng
        tableDetail.getColumnModel().getColumn(4).setPreferredWidth(100);  // HSD
        tableDetail.getColumnModel().getColumn(5).setPreferredWidth(80);   // Đơn vị
        tableDetail.getColumnModel().getColumn(6).setPreferredWidth(80);   // Số lượng
        tableDetail.getColumnModel().getColumn(7).setPreferredWidth(100);  // Đơn giá
        tableDetail.getColumnModel().getColumn(8).setPreferredWidth(120);  // Thành tiền
        tableDetail.getColumnModel().getColumn(9).setPreferredWidth(150);  // Lý do

        // Center align cho các cột số
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        tableDetail.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tableDetail.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        tableDetail.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);

        // Right align cho các cột tiền
        javax.swing.table.DefaultTableCellRenderer rightRenderer = new javax.swing.table.DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        tableDetail.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
        tableDetail.getColumnModel().getColumn(8).setCellRenderer(rightRenderer);

        scrollTableDetail.setViewportView(tableDetail);
        scrollTableDetail.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));

        // Cập nhật jPanel1 với header và table
        jPanel1.removeAll();
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(headerInfoPanel, java.awt.BorderLayout.NORTH);
        jPanel1.add(scrollTableDetail, java.awt.BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();

        modalPurchaseOrderDetail.setLocationRelativeTo(null);
        modalPurchaseOrderDetail.setVisible(true);
    }//GEN-LAST:event_btnViewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel headerPanel;
    private com.toedter.calendar.JDateChooser jDateFrom;
    private com.toedter.calendar.JDateChooser jDateTo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JDialog modalPurchaseOrderDetail;
    private javax.swing.JPanel pnAll;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JScrollPane scrollTableDetail;
    private javax.swing.JTextField txtEmp;
    private javax.swing.JButton txtOrder;
    // End of variables declaration//GEN-END:variables

}
