/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.nhanvien.qlKhachHang;

/**
 *
 * @author User
 */
public class QLKhachHangGUI extends javax.swing.JPanel {

    /**
     * Creates new form QLKhachHangGUI
     */
    public QLKhachHangGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_ToolBar1 = new vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.nhanvien.qlKhachHang.Panel_ToolBar();
        panel_TableKhachHang1 = new vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.nhanvien.qlKhachHang.Panel_TableKhachHang();

        setLayout(new java.awt.BorderLayout(0, 15));
        add(panel_ToolBar1, java.awt.BorderLayout.PAGE_START);
        add(panel_TableKhachHang1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.nhanvien.qlKhachHang.Panel_TableKhachHang panel_TableKhachHang1;
    private vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.nhanvien.qlKhachHang.Panel_ToolBar panel_ToolBar1;
    // End of variables declaration//GEN-END:variables
}
