/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.quanly.quanlykhuyenmai;

import vn.edu.iuh.fit.iuhpharmacitymanagement.bus.KhuyenMaiBUS;
import vn.edu.iuh.fit.iuhpharmacitymanagement.bus.KhachHangBUS;
import vn.edu.iuh.fit.iuhpharmacitymanagement.dao.KhachHangDAO;
import vn.edu.iuh.fit.iuhpharmacitymanagement.dao.DonHangDAO;
import com.formdev.flatlaf.FlatClientProperties;
import java.util.Arrays;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.SwingUtilities;
import vn.edu.iuh.fit.iuhpharmacitymanagement.common.TableDesign;
import vn.edu.iuh.fit.iuhpharmacitymanagement.entity.KhuyenMai;
import vn.edu.iuh.fit.iuhpharmacitymanagement.entity.KhachHang;
import vn.edu.iuh.fit.iuhpharmacitymanagement.util.EmailUtil;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.text.DecimalFormat;
import javax.swing.JTable;
import raven.toast.Notifications;
import javax.swing.JOptionPane;
import vn.edu.iuh.fit.iuhpharmacitymanagement.constant.LoaiKhuyenMai;

/**
 *
 * @author PhamTra
 */
public class GD_QuanLyKhuyenMai extends javax.swing.JPanel {

    private final KhuyenMaiBUS khuyenMaiBUS;
    private final KhachHangBUS khachHangBUS;
    private TableDesign tableDesign;
    private DecimalFormat percentFormat = new DecimalFormat("#.##%");

    public GD_QuanLyKhuyenMai() {
        khuyenMaiBUS = new KhuyenMaiBUS();
        khachHangBUS = new KhachHangBUS(new KhachHangDAO(), new DonHangDAO());
        initComponents();
        setUIManager();
        fillTable();
    }

    private void setUIManager() {
        txtMaKhuyenMai.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mã khuyến mãi");
        UIManager.put("Button.arc", 10);
        
        // Style cho các button chức năng
        btnThem.putClientProperty(FlatClientProperties.STYLE, ""
                + "background:#28A745;"
                + "foreground:#FFFFFF;"
                + "hoverBackground:#218838;"
                + "pressedBackground:#1E7E34;"
                + "arc:10;"
                + "borderWidth:0");
        
        btnSua.putClientProperty(FlatClientProperties.STYLE, ""
                + "background:#FFC107;"
                + "foreground:#000000;"
                + "hoverBackground:#E0A800;"
                + "pressedBackground:#C69500;"
                + "arc:10;"
                + "borderWidth:0");
        
        btnXoa.putClientProperty(FlatClientProperties.STYLE, ""
                + "background:#DC3545;"
                + "foreground:#FFFFFF;"
                + "hoverBackground:#C82333;"
                + "pressedBackground:#BD2130;"
                + "arc:10;"
                + "borderWidth:0");
        
        btnXemChiTiet.putClientProperty(FlatClientProperties.STYLE, ""
                + "background:#17A2B8;"
                + "foreground:#FFFFFF;"
                + "hoverBackground:#138496;"
                + "pressedBackground:#117A8B;"
                + "arc:10;"
                + "borderWidth:0");
    }

    private void fillTable() {
        String[] headers = {"Mã khuyến mãi", "Tên khuyến mãi", "Ngày bắt đầu",
            "Ngày kết thúc", "Giảm giá", "Loại khuyến mãi", "Trạng thái"};
        List<Integer> tableWidths = Arrays.asList(120, 200, 120, 120, 100, 120, 100);
        tableDesign = new TableDesign(headers, tableWidths);
        scrollTable.setViewportView(tableDesign.getTable());
        scrollTable.setBorder(BorderFactory.createEmptyBorder(15, 20, 20, 20));
        List<KhuyenMai> danhSach = khuyenMaiBUS.getAllKhuyenMai();
        fillContent(danhSach);
    }

    private void fillContent(List<KhuyenMai> danhSach) {
        tableDesign.getModelTable().setRowCount(0);
        for (KhuyenMai km : danhSach) {
            String loaiKM = km.getLoaiKhuyenMai() == LoaiKhuyenMai.SAN_PHAM ? "Sản phẩm" : "Đơn hàng";
            String trangThai = km.isTrangThai() ? "Còn hạn" : "Hết hạn";
            
            tableDesign.getModelTable().addRow(new Object[]{
                km.getMaKhuyenMai(),
                km.getTenKhuyenMai(),
                formatDate(km.getNgayBatDau()),
                formatDate(km.getNgayKetThuc()),
                percentFormat.format(km.getGiamGia()),
                loaiKM,
                trangThai
            });
        }
    }

    private String formatDate(LocalDate date) {
        if (date == null) {
            return "";
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return date.format(formatter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAll = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXemChiTiet = new javax.swing.JButton();
        txtMaKhuyenMai = new javax.swing.JTextField();
        cboLoaiKhuyenMai = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        pnAll.setBackground(new java.awt.Color(255, 255, 255));
        pnAll.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(232, 232, 232)));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("THÊM");
        btnThem.setPreferredSize(new java.awt.Dimension(100, 40));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setText("SỬA");
        btnSua.setPreferredSize(new java.awt.Dimension(100, 40));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setPreferredSize(new java.awt.Dimension(100, 40));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXemChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXemChiTiet.setText("XEM CHI TIẾT");
        btnXemChiTiet.setPreferredSize(new java.awt.Dimension(150, 40));
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        txtMaKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cboLoaiKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboLoaiKhuyenMai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Sản phẩm", "Đơn hàng" }));

        btnTimKiem.setBackground(new java.awt.Color(115, 165, 71));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setPreferredSize(new java.awt.Dimension(120, 40));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(115, 165, 71));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Phát hành khuyến mãi");
        btnLamMoi.setPreferredSize(new java.awt.Dimension(220, 40));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cboLoaiKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoaiKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        headerPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        pnAll.add(headerPanel, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(1226, 174));
        jPanel4.setPreferredSize(new java.awt.Dimension(1226, 174));
        jPanel4.setLayout(new java.awt.BorderLayout());

        // Thêm tiêu đề "DANH SÁCH THÔNG TIN KHUYẾN MÃI"
        javax.swing.JPanel titlePanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 12));
        titlePanel.setBackground(new java.awt.Color(23, 162, 184)); // Màu xanh cyan
        javax.swing.JLabel lblTitle = new javax.swing.JLabel("DANH SÁCH THÔNG TIN KHUYẾN MÃI");
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16));
        lblTitle.setForeground(new java.awt.Color(255, 255, 255)); // Chữ màu trắng
        titlePanel.add(lblTitle);
        jPanel4.add(titlePanel, java.awt.BorderLayout.NORTH);

        jPanel4.add(scrollTable, java.awt.BorderLayout.CENTER);

        pnAll.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(pnAll);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // Mở dialog thêm khuyến mãi
        ThemKhuyenMaiDialog dialog = new ThemKhuyenMaiDialog((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        dialog.setVisible(true);
        
        // Nếu thêm thành công thì refresh table
        if (dialog.isThemThanhCong()) {
            fillTable();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        JTable table = tableDesign.getTable();
        int selectedRow = table.getSelectedRow();
        if (selectedRow < 0) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Hãy chọn khuyến mãi cần sửa!");
            return;
        }
        
        // Lấy thông tin khuyến mãi được chọn
        String maKhuyenMai = (String) tableDesign.getModelTable().getValueAt(selectedRow, 0);
        List<KhuyenMai> danhSach = khuyenMaiBUS.getAllKhuyenMai();
        KhuyenMai kmCanSua = danhSach.stream()
            .filter(km -> km.getMaKhuyenMai().equals(maKhuyenMai))
            .findFirst()
            .orElse(null);
        
        if (kmCanSua == null) {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Không tìm thấy khuyến mãi!");
            return;
        }
        
        // Mở dialog sửa khuyến mãi
        SuaKhuyenMaiDialog dialog = new SuaKhuyenMaiDialog((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true, kmCanSua);
        dialog.setVisible(true);
        
        // Nếu sửa thành công thì refresh table
        if (dialog.isSuaThanhCong()) {
            fillTable();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        JTable table = tableDesign.getTable();
        int selectedRow = table.getSelectedRow();
        if (selectedRow < 0) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Hãy chọn khuyến mãi cần xem chi tiết!");
            return;
        }
        
        // Lấy thông tin khuyến mãi được chọn
        String maKhuyenMai = (String) tableDesign.getModelTable().getValueAt(selectedRow, 0);
        List<KhuyenMai> danhSach = khuyenMaiBUS.getAllKhuyenMai();
        KhuyenMai kmCanXem = danhSach.stream()
            .filter(km -> km.getMaKhuyenMai().equals(maKhuyenMai))
            .findFirst()
            .orElse(null);
        
        if (kmCanXem == null) {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Không tìm thấy khuyến mãi!");
            return;
        }
        
        // Mở dialog xem chi tiết khuyến mãi
        XemChiTietKhuyenMaiDialog dialog = new XemChiTietKhuyenMaiDialog((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true, kmCanXem);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnXemChiTietActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        JTable table = tableDesign.getTable();
        int selectedRow = table.getSelectedRow();
        if (selectedRow < 0) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Hãy chọn khuyến mãi cần xóa!");
            return;
        }
        
        String maKhuyenMai = (String) tableDesign.getModelTable().getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Bạn có chắc chắn muốn xóa khuyến mãi " + maKhuyenMai + "?",
            "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                boolean success = khuyenMaiBUS.xoaKhuyenMai(maKhuyenMai);
                if (success) {
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, "Xóa khuyến mãi thành công!");
                    fillTable(); // Refresh table
                } else {
                    Notifications.getInstance().show(Notifications.Type.ERROR, "Xóa khuyến mãi thất bại!");
                }
            } catch (Exception e) {
                Notifications.getInstance().show(Notifications.Type.ERROR, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String maKhuyenMai = txtMaKhuyenMai.getText().trim();
        String loaiKM = (String) cboLoaiKhuyenMai.getSelectedItem();
        
        List<KhuyenMai> danhSach = khuyenMaiBUS.getAllKhuyenMai();
        
        // Lọc theo mã khuyến mãi
        if (!maKhuyenMai.isEmpty()) {
            danhSach = danhSach.stream()
                .filter(km -> km.getMaKhuyenMai().toLowerCase().contains(maKhuyenMai.toLowerCase()))
                .toList();
        }
        
        // Lọc theo loại khuyến mãi
        if (!loaiKM.equals("Tất cả")) {
            LoaiKhuyenMai loai = loaiKM.equals("Sản phẩm") ? LoaiKhuyenMai.SAN_PHAM : LoaiKhuyenMai.DON_HANG;
            danhSach = danhSach.stream()
                .filter(km -> km.getLoaiKhuyenMai() == loai)
                .toList();
        }
        
        fillContent(danhSach);
        
        if (danhSach.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.INFO, "Không tìm thấy khuyến mãi nào!");
        } else {
            Notifications.getInstance().show(Notifications.Type.SUCCESS, "Tìm thấy " + danhSach.size() + " khuyến mãi!");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // Kiểm tra có chọn khuyến mãi không        
        JTable table = tableDesign.getTable();
        int selectedRow = table.getSelectedRow();
        if (selectedRow < 0) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Hãy chọn khuyến mãi cần phát hành!");
            return;
        }
        
        // Lấy thông tin khuyến mãi được chọn
        String maKhuyenMai = (String) tableDesign.getModelTable().getValueAt(selectedRow, 0);
        List<KhuyenMai> danhSach = khuyenMaiBUS.getAllKhuyenMai();
        KhuyenMai khuyenMai = danhSach.stream()
            .filter(km -> km.getMaKhuyenMai().equals(maKhuyenMai))
            .findFirst()
            .orElse(null);
        
        if (khuyenMai == null) {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Không tìm thấy khuyến mãi!");
            return;
        }
        
        // Kiểm tra khuyến mãi có còn hạn không
        if (!khuyenMai.isTrangThai()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Khuyến mãi đã hết hạn, không thể phát hành!");
            return;
        }
        
        // Xác nhận phát hành
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Bạn có chắc chắn muốn gửi email khuyến mãi này đến tất cả khách hàng?\n" +
            "Khuyến mãi: " + khuyenMai.getTenKhuyenMai(),
            "Xác nhận phát hành",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Kiểm tra cấu hình email
        if (!EmailUtil.kiemTraCauHinhEmail()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, 
                "Chưa cấu hình email! Vui lòng cấu hình email trong EmailUtil.java");
            return;
        }
        
        // Lấy danh sách khách hàng có email
        List<KhachHang> danhSachKhachHang = khachHangBUS.getAllKhachHang();
        List<KhachHang> khachHangCoEmail = danhSachKhachHang.stream()
            .filter(kh -> kh.getEmail() != null && !kh.getEmail().trim().isEmpty())
            .toList();
        
        if (khachHangCoEmail.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Không có khách hàng nào có email!");
            return;
        }
        
        // Hiển thị thông báo bắt đầu
        Notifications.getInstance().show(Notifications.Type.INFO, 
            "Đang gửi khuyến mãi đến các khách hàng có trong hệ thống...");
        
        // Gửi email trong background thread
        new Thread(() -> {
            int soEmailThanhCong = 0;
            int soEmailThatBai = 0;
            
            for (KhachHang kh : khachHangCoEmail) {
                boolean success = EmailUtil.guiEmailKhuyenMai(kh, khuyenMai);
                if (success) {
                    soEmailThanhCong++;
                } else {
                    soEmailThatBai++;
                }
                
                // Delay giữa các email để tránh spam
                try {
                    Thread.sleep(100); // 0.1 giây
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
            
            final int thanhCong = soEmailThanhCong;
            final int thatBai = soEmailThatBai;
            
            // Hiển thị kết quả trên UI thread
            SwingUtilities.invokeLater(() -> {
                if (thatBai == 0) {
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, 
                        "Đã gửi thành công");
                } else {
                    Notifications.getInstance().show(Notifications.Type.WARNING, 
                        "Hoàn thành! Thành công: " + thanhCong + ", Thất bại: " + thatBai);
                }
            });
        }).start();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiKhuyenMai;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnAll;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTextField txtMaKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
