/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.nhanvien.thongtinnhanvien;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import vn.edu.iuh.fit.iuhpharmacitymanagement.entity.NhanVien;
import vn.edu.iuh.fit.iuhpharmacitymanagement.session.SessionManager;

import javax.swing.*;

/**
 *
 * @author User
 */
public class GD_ThongTinCaNhan extends javax.swing.JPanel {

    /**
     * Creates new form GD_ThongTinCaNhan
     */
    public GD_ThongTinCaNhan(boolean isManager) {
        initComponents();
        try {
            NhanVien nv = SessionManager.getInstance().getCurrentUser();
            
            thongTinCoBanPanel1.loadAndConfigure(isManager, nv);
            
            // TODO: Tải dữ liệu cho các panel còn lại
            // thongKeNhanhPanel1.loadData(...);
            // lichSuChamCongPanel1.loadData(...);
        } catch (Exception e) {
             e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu người dùng!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        thongTinCoBanPanel1 = new vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.nhanvien.thongtinnhanvien.ThongTinCoBanPanel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        add(thongTinCoBanPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.nhanvien.thongtinnhanvien.ThongTinCoBanPanel thongTinCoBanPanel1;
    // End of variables declaration//GEN-END:variables
}
