/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.nhanvien.thongtinnhanvien;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.InvalidPathException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Base64;
import java.util.Optional;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import raven.toast.Notifications;
import vn.edu.iuh.fit.iuhpharmacitymanagement.dao.TaiKhoanDAO;
import vn.edu.iuh.fit.iuhpharmacitymanagement.entity.NhanVien;
import vn.edu.iuh.fit.iuhpharmacitymanagement.session.SessionManager;
import vn.edu.iuh.fit.iuhpharmacitymanagement.util.PasswordUtil;

/**
 *
 * @author User
 */
public class ThongTinCoBanPanel extends javax.swing.JPanel {

    private String currentAnhNhanVien;
    private static final Dimension CHANGE_PASSWORD_DIALOG_SIZE = new Dimension(700, 500);

    /**
     * Creates new form ThongTinCoBanPanel
     */
    public ThongTinCoBanPanel() {
        initComponents();

        btnDoiMatKhau.setVisible(true);
        resetChangePasswordFields();
        styleChangePasswordDialog();
    }

//    private void styleReadOnlyTextField(javax.swing.JTextField textField) {
//    textField.setEditable(false);
//    textField.setBorder(null);
//    textField.setBackground(this.getBackground());
//    textField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // Font lớn hơn
//    textField.setForeground(new java.awt.Color(51, 51, 51)); // Màu chữ đậm hơn
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jdiaDoiPass = new javax.swing.JDialog();
        pnlDoiMatKhau = new javax.swing.JPanel();
        lblDialogTitle = new javax.swing.JLabel();
        lblOldPassTitle = new javax.swing.JLabel();
        txtMkCu = new javax.swing.JPasswordField();
        lblNewPassTitle = new javax.swing.JLabel();
        txtMkMoi = new javax.swing.JPasswordField();
        lblConfirmPassTitle = new javax.swing.JLabel();
        txtXacNhanMkMoi = new javax.swing.JPasswordField();
        pnlNut = new javax.swing.JPanel();
        lblQuayLai = new javax.swing.JLabel();
        btnXNDoiMatKhau = new javax.swing.JButton();
        lblAvatar = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblIconPhone = new javax.swing.JLabel();
        lblPhoneTitle = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblIconEmail = new javax.swing.JLabel();
        lblEmailTitle = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblIconAddress = new javax.swing.JLabel();
        lblAddressTitle = new javax.swing.JLabel();
        scrAddress = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblIconCccd = new javax.swing.JLabel();
        lblCccdTitle = new javax.swing.JLabel();
        txtCccd = new javax.swing.JTextField();
        lblGenderIcon = new javax.swing.JLabel();
        lblGenderTitle = new javax.swing.JLabel();
        lblGenderValue = new javax.swing.JLabel();
        btnDoiMatKhau = new javax.swing.JButton();

        pnlDoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoiMatKhau.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 20, 30));
        pnlDoiMatKhau.setLayout(new java.awt.GridBagLayout());

        lblDialogTitle.setText("ĐỔI MẬT KHẨU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        pnlDoiMatKhau.add(lblDialogTitle, gridBagConstraints);

        lblOldPassTitle.setText("Mật khẩu cũ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        pnlDoiMatKhau.add(lblOldPassTitle, gridBagConstraints);

        txtMkCu.setMinimumSize(new java.awt.Dimension(300, 22));
        txtMkCu.setPreferredSize(new java.awt.Dimension(64, 40));
        txtMkCu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMkCuFocusLost(evt);
            }
        });
        txtMkCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMkCuMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlDoiMatKhau.add(txtMkCu, gridBagConstraints);

        lblNewPassTitle.setText("Mật khẩu mới");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        pnlDoiMatKhau.add(lblNewPassTitle, gridBagConstraints);

        txtMkMoi.setPreferredSize(new java.awt.Dimension(300, 40));
        txtMkMoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMkMoiFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlDoiMatKhau.add(txtMkMoi, gridBagConstraints);

        lblConfirmPassTitle.setText("Xác nhận mật khẩu mới");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        pnlDoiMatKhau.add(lblConfirmPassTitle, gridBagConstraints);

        txtXacNhanMkMoi.setPreferredSize(new java.awt.Dimension(300, 40));
        txtXacNhanMkMoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtXacNhanMkMoiFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlDoiMatKhau.add(txtXacNhanMkMoi, gridBagConstraints);

        pnlNut.setOpaque(false);
        pnlNut.setLayout(new java.awt.BorderLayout(50, 0));

        lblQuayLai.setText("Quay lại");
        pnlNut.add(lblQuayLai, java.awt.BorderLayout.LINE_START);

        btnXNDoiMatKhau.setText("Xác nhận đổi mật khẩu");
        btnXNDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXNDoiMatKhauActionPerformed(evt);
            }
        });
        pnlNut.add(btnXNDoiMatKhau, java.awt.BorderLayout.LINE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlDoiMatKhau.add(pnlNut, gridBagConstraints);

        javax.swing.GroupLayout jdiaDoiPassLayout = new javax.swing.GroupLayout(jdiaDoiPass.getContentPane());
        jdiaDoiPass.getContentPane().setLayout(jdiaDoiPassLayout);
        jdiaDoiPassLayout.setHorizontalGroup(
            jdiaDoiPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdiaDoiPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdiaDoiPassLayout.setVerticalGroup(
            jdiaDoiPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdiaDoiPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.GridBagLayout());

        lblAvatar.setText("lblAv");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(lblAvatar, gridBagConstraints);

        lblTenNV.setText("ten");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(lblTenNV, gridBagConstraints);

        lblMa.setText("ma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        add(lblMa, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        add(jSeparator1, gridBagConstraints);

        lblIconPhone.setText("conPhone");
        lblIconPhone.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        add(lblIconPhone, gridBagConstraints);

        lblPhoneTitle.setText("phoneTitle");
        lblPhoneTitle.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        add(lblPhoneTitle, gridBagConstraints);

        txtPhone.setText("txtPhone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(txtPhone, gridBagConstraints);

        lblIconEmail.setText("lblIconEmail");
        lblIconEmail.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        add(lblIconEmail, gridBagConstraints);

        lblEmailTitle.setText("lblEmailTitle");
        lblEmailTitle.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        add(lblEmailTitle, gridBagConstraints);

        txtEmail.setText("txtEmail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(txtEmail, gridBagConstraints);

        lblIconAddress.setText("lblIconAddress");
        lblIconAddress.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        add(lblIconAddress, gridBagConstraints);

        lblAddressTitle.setText("lblAddressTitle");
        lblAddressTitle.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        add(lblAddressTitle, gridBagConstraints);

        txtAddress.setEditable(false);
        txtAddress.setColumns(20);
        txtAddress.setLineWrap(true);
        txtAddress.setRows(3);
        txtAddress.setWrapStyleWord(true);
        scrAddress.setViewportView(txtAddress);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(scrAddress, gridBagConstraints);

        lblIconCccd.setText("lblIconCccd");
        lblIconCccd.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        add(lblIconCccd, gridBagConstraints);

        lblCccdTitle.setText("lblCccdTitle");
        lblCccdTitle.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        add(lblCccdTitle, gridBagConstraints);

        txtCccd.setText("txtCccd");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(txtCccd, gridBagConstraints);

        lblGenderIcon.setText("lblGenderIcon");
        lblGenderIcon.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        add(lblGenderIcon, gridBagConstraints);

        lblGenderTitle.setText("lblGenderTitle");
        lblGenderTitle.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        add(lblGenderTitle, gridBagConstraints);

        lblGenderValue.setText("lblGenderValue");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(lblGenderValue, gridBagConstraints);

        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(btnDoiMatKhau, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public void loadAndConfigure(boolean isManager, NhanVien nv) {
        styleComponents();

        if (nv != null) {
            populateData(nv);
        } else {
            lblTenNV.setText("Không có dữ liệu người dùng");
            lblMa.setText("");
        }
    }

    private void populateData(NhanVien nv) {
        currentAnhNhanVien = nv.getAnhNhanVien();

        String ten = nv.getTenNhanVien();
        lblTenNV.setText(ten);
        lblMa.setText(nv.getMaNhanVien());
        updateGenderDisplay(nv.getGioiTinh());
        txtPhone.setText(nv.getSoDienThoai());
        txtEmail.setText(nv.getEmail());
        txtCccd.setText(nv.getCccd());
        txtAddress.setText(nv.getDiaChi());
        updateAvatarPreview(currentAnhNhanVien, ten);
    }

    public void setTenNhanVien(String ten) {
        lblTenNV.setText(ten);
        updateAvatarPreview(currentAnhNhanVien, ten);
    }

    public void setMa(String maNV) {
        lblMa.setText(maNV);
    }

    public void setSoDienThoai(String sdt) {
        txtPhone.setText(sdt);
    }

    public void setEmail(String email) {
        txtEmail.setText(email);
    }

    public void setDiaChi(String diaChi) {
        txtAddress.setText(diaChi);
    }

    private void styleComponents() {
        lblAvatar.setOpaque(true);
        lblAvatar.setPreferredSize(new Dimension(160, 160));
        lblAvatar.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc: 80;"
                + "font: 700 48;"
                + "foreground: #1F1F1F;"
                + "borderColor: #E0E0E0;"
                + "borderWidth: 2;"
                + "background: #F5F5F5;");
        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 32));
        lblTenNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMa.setFont(new java.awt.Font("Segoe UI", 0, 18));
        lblMa.setForeground(java.awt.Color.GRAY);
        lblMa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblGenderTitle.setText("Giới tính:");
        lblGenderTitle.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lblGenderValue.setFont(new java.awt.Font("Segoe UI", 0, 18));
        lblGenderValue.setForeground(new java.awt.Color(51, 51, 51));

        styleReadOnlyTextField(txtPhone);
        styleReadOnlyTextField(txtEmail);
        styleReadOnlyTextField(txtCccd);
        txtAddress.setBackground(this.getBackground());
        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 18));
        txtAddress.setForeground(new java.awt.Color(51, 51, 51));
        scrAddress.setOpaque(false);
        scrAddress.getViewport().setOpaque(false);
        scrAddress.setBorder(null);

        setIcon(lblIconPhone, "/img/icons/phone.svg", "📞");
        setIcon(lblIconEmail, "/img/icons/email.svg", "📧");
        setIcon(lblIconAddress, "/img/icons/address.svg", "🏠");
        setIcon(lblIconCccd, "/img/icons/user_icon.svg", "🆔");
        setIcon(lblGenderIcon, "/img/icons/user_icon.svg", "👤");

        lblPhoneTitle.setText("Điện thoại:");
        lblPhoneTitle.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lblEmailTitle.setText("Email:");
        lblEmailTitle.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lblAddressTitle.setText("Địa chỉ:");
        lblAddressTitle.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lblCccdTitle.setText("CCCD:");
        lblCccdTitle.setFont(new java.awt.Font("Segoe UI", 1, 18));

        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 16));
        btnDoiMatKhau.setPreferredSize(new java.awt.Dimension(200, 45));
        btnDoiMatKhau.putClientProperty(com.formdev.flatlaf.FlatClientProperties.STYLE, ""
                + "arc: 10;"
                + "background: $Component.accentColor;"
                + "foreground: #FFFFFF;");
    }

    private void updateGenderDisplay(String gioiTinh) {
        String displayGender = (gioiTinh != null && !gioiTinh.isBlank()) ? gioiTinh : "Không rõ";
        lblGenderValue.setText(displayGender);
        if (gioiTinh == null) {
            setIcon(lblGenderIcon, "/img/icons/user_icon.svg", "👤");
            return;
        }
        if (gioiTinh.equalsIgnoreCase("Nam")) {
            setIcon(lblGenderIcon, "/img/icons/male.svg", "♂");
        } else if (gioiTinh.equalsIgnoreCase("Nữ")) {
            setIcon(lblGenderIcon, "/img/icons/female.svg", "♀");
        } else {
            setIcon(lblGenderIcon, "/img/icons/user_icon.svg", "⚧");
        }
    }

    private void updateAvatarPreview(String data, String hoTen) {
        ImageIcon icon = createAvatarIcon(data);
        if (icon != null) {
            lblAvatar.setIcon(icon);
            lblAvatar.setText("");
        } else {
            lblAvatar.setIcon(null);
            lblAvatar.setText(extractInitial(hoTen));
        }
    }

    private ImageIcon createAvatarIcon(String data) {
        BufferedImage image = loadImageFromData(data);
        if (image == null) {
            return null;
        }
        Image scaledImage = image.getScaledInstance(160, 160, Image.SCALE_SMOOTH);
        return new ImageIcon(scaledImage);
    }

    private BufferedImage loadImageFromData(String data) {
        if (data == null) {
            return null;
        }
        String trimmed = data.trim();
        if (trimmed.isEmpty()) {
            return null;
        }
        try {
            if (trimmed.startsWith("http://") || trimmed.startsWith("https://")) {
                return ImageIO.read(URI.create(trimmed).toURL());
            }
        } catch (IOException e) {
            System.err.println("Không thể tải ảnh từ URL: " + e.getMessage());
        }

        try {
            Path path = Paths.get(trimmed);
            if (Files.exists(path)) {
                return ImageIO.read(path.toFile());
            }
        } catch (InvalidPathException | IOException ignored) {
        }

        try {
            URL resourceUrl = getClass().getResource(trimmed);
            if (resourceUrl != null) {
                return ImageIO.read(resourceUrl);
            }
        } catch (IOException ignored) {
        }

        try {
            String base64 = trimmed.contains(",") ? trimmed.substring(trimmed.indexOf(',') + 1) : trimmed;
            byte[] decoded = Base64.getDecoder().decode(base64);
            return ImageIO.read(new ByteArrayInputStream(decoded));
        } catch (IllegalArgumentException | IOException e) {
            System.err.println("Không thể đọc dữ liệu ảnh: " + e.getMessage());
        }
        return null;
    }

    private String extractInitial(String fullName) {
        if (fullName == null || fullName.isBlank()) {
            return "?";
        }
        String[] parts = fullName.trim().split("\\s+");
        for (int i = parts.length - 1; i >= 0; i--) {
            String part = parts[i];
            if (!part.isBlank()) {
                return String.valueOf(Character.toUpperCase(part.charAt(0)));
            }
        }
        return "?";
    }

    private void styleReadOnlyTextField(javax.swing.JTextField textField) {
        textField.setEditable(false);
        textField.setBorder(null);
        textField.setBackground(this.getBackground());
        textField.setFont(new java.awt.Font("Segoe UI", 0, 18));
        textField.setForeground(new java.awt.Color(51, 51, 51));
    }

    private void resetChangePasswordFields() {
        txtMkCu.setText("");
        txtMkMoi.setText("");
        txtXacNhanMkMoi.setText("");
        txtMkCu.putClientProperty("JComponent.outline", null);
        txtMkMoi.putClientProperty("JComponent.outline", null);
        txtXacNhanMkMoi.putClientProperty("JComponent.outline", null);
    }

    private void styleDialogPasswordField(javax.swing.JPasswordField field, String placeholder) {
        field.setFont(new java.awt.Font("Segoe UI", 0, 16));
        field.setPreferredSize(new Dimension(420, 50));
        field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, placeholder);
        field.putClientProperty(FlatClientProperties.STYLE, ""
                + "showRevealButton:true;"
                + "margin:6,14,6,14;"
                + "arc:12;"
                + "borderWidth:1;"
                + "focusWidth:2;"
                + "borderColor:#D5DAE5;"
                + "focusColor:#2563EB;"
                + "background:#F9FAFB;");
    }

    private void styleChangePasswordDialog() {
        jdiaDoiPass.setMinimumSize(CHANGE_PASSWORD_DIALOG_SIZE);
        jdiaDoiPass.setPreferredSize(CHANGE_PASSWORD_DIALOG_SIZE);
        jdiaDoiPass.setSize(CHANGE_PASSWORD_DIALOG_SIZE);
        jdiaDoiPass.setResizable(false);
        jdiaDoiPass.setModal(true);
        jdiaDoiPass.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        jdiaDoiPass.getContentPane().setBackground(Color.WHITE);

        pnlDoiMatKhau.setBackground(Color.WHITE);
        pnlDoiMatKhau.setOpaque(true);
        pnlDoiMatKhau.setPreferredSize(new Dimension(640, 360));
        pnlDoiMatKhau.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new Color(226, 232, 240)),
                javax.swing.BorderFactory.createEmptyBorder(30, 40, 30, 40)
        ));

        java.awt.Font labelFont = new java.awt.Font("Segoe UI", 0, 16);
        lblOldPassTitle.setFont(labelFont);
        lblNewPassTitle.setFont(labelFont);
        lblConfirmPassTitle.setFont(labelFont);

        styleDialogPasswordField(txtMkCu, "Nhập mật khẩu cũ của bạn");
        styleDialogPasswordField(txtMkMoi, "Nhập mật khẩu mới");
        styleDialogPasswordField(txtXacNhanMkMoi, "Xác nhận mật khẩu mới");
        final char bullet = '\u2022';
        txtMkCu.setEchoChar(bullet);
        txtMkMoi.setEchoChar(bullet);
        txtXacNhanMkMoi.setEchoChar(bullet);

        btnXNDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 16));
        btnXNDoiMatKhau.setPreferredSize(new Dimension(240, 48));
        btnXNDoiMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXNDoiMatKhau.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:12;"
                + "background:$Component.accentColor;"
                + "foreground:#FFFFFF;"
                + "borderWidth:0;"
                + "focusWidth:0;"
                + "padding:8,20,8,20;");

        pnlNut.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
    }

    private void requestFocusSafely(java.awt.Component component) {
        if (component == null) {
            return;
        }
        SwingUtilities.invokeLater(() -> {
            Window window = SwingUtilities.getWindowAncestor(component);
            if (window != null) {
                window.toFront();
                window.requestFocus();
            } else if (jdiaDoiPass.isShowing()) {
                jdiaDoiPass.toFront();
                jdiaDoiPass.requestFocus();
            }
            if (component.isDisplayable()) {
                component.requestFocusInWindow();
            } else {
                component.requestFocus();
            }
        });
    }

    private javax.swing.JFrame resolveNotificationFrame() {
        Window activeWindow = jdiaDoiPass.isShowing() ? jdiaDoiPass : SwingUtilities.getWindowAncestor(this);
        if (activeWindow instanceof javax.swing.JFrame frame) {
            return frame;
        }
        if (activeWindow instanceof Dialog dialog) {
            Window owner = dialog.getOwner();
            if (owner instanceof javax.swing.JFrame ownerFrame) {
                return ownerFrame;
            }
        }
        return null;
    }

    private void showDialogNotification(Notifications.Type type, String message) {
        javax.swing.JFrame targetFrame = resolveNotificationFrame();
        Notifications notifications = Notifications.getInstance();
        if (targetFrame != null) {
            notifications.setJFrame(targetFrame);
        }
        notifications.show(type, message);
        if (jdiaDoiPass.isShowing()) {
            jdiaDoiPass.toFront();
        }
    }

    private boolean validateChangePasswordInputs(NhanVien nv) {
        if (nv == null) {
            showDialogNotification(Notifications.Type.ERROR, "Không tìm thấy thông tin người dùng!");
            return false;
        }

        String oldPassword = String.valueOf(txtMkCu.getPassword()).trim();
        String newPassword = String.valueOf(txtMkMoi.getPassword()).trim();
        String confirmPassword = String.valueOf(txtXacNhanMkMoi.getPassword()).trim();

        if (oldPassword.isBlank()) {
            showDialogNotification(Notifications.Type.ERROR, "Hãy nhập mật khẩu cũ!");
            txtMkCu.putClientProperty("JComponent.outline", "error");
            requestFocusSafely(txtMkCu);
            return false;
        }

        Optional<String> storedPassword = new TaiKhoanDAO()
                .findPassByTenDangNhap(nv.getMaNhanVien().toLowerCase());
        if (storedPassword.isEmpty() || !PasswordUtil.verify(oldPassword, storedPassword.get())) {
            showDialogNotification(Notifications.Type.ERROR, "Mật khẩu cũ không chính xác!");
            txtMkCu.putClientProperty("JComponent.outline", "error");
            requestFocusSafely(txtMkCu);
            return false;
        }
        txtMkCu.putClientProperty("JComponent.outline", "success");

        if (newPassword.isBlank()) {
            showDialogNotification(Notifications.Type.ERROR, "Vui lòng nhập mật khẩu mới!");
            txtMkMoi.putClientProperty("JComponent.outline", "error");
            requestFocusSafely(txtMkMoi);
            return false;
        }

        String REGEX_PASSWORD = "^(?=.*[0-9])(?=.*[@#$^*]).{6,}$";
        String MAT_KHAU_SAI = "Mật khẩu phải từ 6 ký tự trở lên, có ít nhất 1 chữ số và 1 ký tự đặc biệt (@#$^*)";
        if (!newPassword.matches(REGEX_PASSWORD)) {
            showDialogNotification(Notifications.Type.ERROR, MAT_KHAU_SAI);
            txtMkMoi.putClientProperty("JComponent.outline", "error");
            requestFocusSafely(txtMkMoi);
            return false;
        }
        txtMkMoi.putClientProperty("JComponent.outline", "success");

        if (confirmPassword.isBlank()) {
            showDialogNotification(Notifications.Type.ERROR, "Vui lòng xác nhận mật khẩu mới!");
            txtXacNhanMkMoi.putClientProperty("JComponent.outline", "error");
            requestFocusSafely(txtXacNhanMkMoi);
            return false;
        }

        if (!newPassword.equals(confirmPassword)) {
            showDialogNotification(Notifications.Type.ERROR, "Mật khẩu xác nhận chưa trùng khớp!");
            txtXacNhanMkMoi.putClientProperty("JComponent.outline", "error");
            requestFocusSafely(txtXacNhanMkMoi);
            return false;
        }
        txtXacNhanMkMoi.putClientProperty("JComponent.outline", "success");

        return true;
    }

    private void setIcon(javax.swing.JLabel label, String path, String fallbackText) {
        try {
            java.net.URL iconUrl = getClass().getResource(path);
            if (iconUrl != null) {
                label.setText("");
                label.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon(iconUrl).derive(24, 24));
            } else {
                System.err.println("Không tìm thấy icon: " + path);
                label.setText(fallbackText);
            }
        } catch (Exception e) {
            System.err.println("Lỗi khi load icon: " + path);
            label.setText(fallbackText);
        }
    }

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed

        styleChangePasswordDialog();
        resetChangePasswordFields();

        jdiaDoiPass.setTitle("Đổi Mật Khẩu");
        jdiaDoiPass.pack();
        jdiaDoiPass.setSize(CHANGE_PASSWORD_DIALOG_SIZE);
        jdiaDoiPass.setLocationRelativeTo(this);
        jdiaDoiPass.setVisible(true);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed
    private void btnXNDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXNDoiMatKhauActionPerformed
        NhanVien nv = SessionManager.getInstance().getCurrentUser();
        if (!validateChangePasswordInputs(nv)) {
                return;
            }

        String newPassword = String.valueOf(txtMkMoi.getPassword());
        if (new TaiKhoanDAO().resetMatKhau(nv.getMaNhanVien().toLowerCase(), newPassword)) {
            showDialogNotification(Notifications.Type.SUCCESS, "Cập nhật mật khẩu thành công!");
                jdiaDoiPass.dispose();
        } else {
            showDialogNotification(Notifications.Type.ERROR, "Không thể cập nhật mật khẩu. Vui lòng thử lại!");
        }

    }//GEN-LAST:event_btnXNDoiMatKhauActionPerformed

    private void txtMkCuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMkCuMouseExited
//        javax.swing.JFrame parentFrame = (javax.swing.JFrame) SwingUtilities.getWindowAncestor(this);
//        String maNhanVien = SessionManager.getInstance().getCurrentUser().getMaNhanVien().toLowerCase();
//        TaiKhoan tk = new TaiKhoanDAO().findById(maNhanVien).get();
//        if (!String.valueOf(txtMkCu.getPassword()).equalsIgnoreCase(maNhanVien)) {
//            Notifications.getInstance().setJFrame(parentFrame);
//            Notifications.getInstance().show(Notifications.Type.ERROR, "Mật khẩu cũ không đúng!");
//            //txtMkCu.requestFocus();
//            return;
//        }
    }//GEN-LAST:event_txtMkCuMouseExited

    private void txtMkCuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMkCuFocusLost
        // No-op: chỉ kiểm tra khi bấm xác nhận
    }//GEN-LAST:event_txtMkCuFocusLost

    private void txtMkMoiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMkMoiFocusLost
        // No-op: chỉ kiểm tra khi bấm xác nhận
    }//GEN-LAST:event_txtMkMoiFocusLost

    private void txtXacNhanMkMoiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtXacNhanMkMoiFocusLost
        // No-op: chỉ kiểm tra khi bấm xác nhận
    }//GEN-LAST:event_txtXacNhanMkMoiFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnXNDoiMatKhau;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JDialog jdiaDoiPass;
    private javax.swing.JLabel lblAddressTitle;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblCccdTitle;
    private javax.swing.JLabel lblConfirmPassTitle;
    private javax.swing.JLabel lblDialogTitle;
    private javax.swing.JLabel lblEmailTitle;
    private javax.swing.JLabel lblGenderIcon;
    private javax.swing.JLabel lblGenderTitle;
    private javax.swing.JLabel lblGenderValue;
    private javax.swing.JLabel lblIconAddress;
    private javax.swing.JLabel lblIconEmail;
    private javax.swing.JLabel lblIconCccd;
    private javax.swing.JLabel lblIconPhone;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblNewPassTitle;
    private javax.swing.JLabel lblOldPassTitle;
    private javax.swing.JLabel lblPhoneTitle;
    private javax.swing.JLabel lblQuayLai;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JPanel pnlDoiMatKhau;
    private javax.swing.JPanel pnlNut;
    private javax.swing.JScrollPane scrAddress;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtCccd;
    private javax.swing.JPasswordField txtMkCu;
    private javax.swing.JPasswordField txtMkMoi;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JPasswordField txtXacNhanMkMoi;
    // End of variables declaration//GEN-END:variables
}
