/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.login;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.Optional;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import raven.toast.Notifications;
import vn.edu.iuh.fit.iuhpharmacitymanagement.dao.NhanVienDAO;
import vn.edu.iuh.fit.iuhpharmacitymanagement.dao.TaiKhoanDAO;
import vn.edu.iuh.fit.iuhpharmacitymanagement.util.EmailUtil;

/**
 *
 * @author User
 */
public class ForgotPasswordPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginFormPanel
     */
    private Image backgroundImage;

    public ForgotPasswordPanel() {
        initComponents();
        backgroundImage = new ImageIcon(getClass().getResource("/img/LoginImage.png")).getImage();
        setOpaque(false); // Đảm bảo panel cho phép hiển thị ảnh nền
        contentPanel.setOpaque(true);
        contentPanel.setBackground(new java.awt.Color(255, 255, 255, 180));
        contentPanel.putClientProperty(FlatClientProperties.STYLE,
                "background:rgba(255,255,255,178)");

        contentPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1, true),
                javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));

        btnDangNhap.putClientProperty("JButton.buttonType", "primary"); // không hoạt động nhưng mà đừng xóa :v        
        txtTenDangNhap.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new com.formdev.flatlaf.extras.FlatSVGIcon("img/user_icon.svg"));
        txtEmail.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new com.formdev.flatlaf.extras.FlatSVGIcon("img/icons/email.svg"));
        contentPanel.setFocusable(true);
        contentPanel.requestFocusInWindow();
        //addPlayhoder(txtTenDangNhap);

        // Tự động focus vào ô tài khoản khi panel được hiển thị
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent evt) {
                // Sử dụng Timer để đảm bảo form đã render hoàn toàn
                javax.swing.Timer timer = new javax.swing.Timer(50, e -> {
                    txtTenDangNhap.requestFocus();
                });
                timer.setRepeats(false);
                timer.start();
            }
        });

        lblQuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                java.awt.Window window = SwingUtilities.getWindowAncestor(ForgotPasswordPanel.this);
                if (window instanceof javax.swing.JFrame frame) {
                    frame.getContentPane().removeAll();
                    frame.getContentPane().add(new LoginFormPanel());
                    frame.revalidate();
                    frame.repaint();
                }
            }
        });

        // Thêm HierarchyListener để đảm bảo focus khi form được thêm vào container
        addHierarchyListener(e -> {
            if ((e.getChangeFlags() & java.awt.event.HierarchyEvent.SHOWING_CHANGED) != 0
                    && isShowing()) {
                SwingUtilities.invokeLater(() -> txtTenDangNhap.requestFocus());
            }
        });
        txtTenDangNhap.setForeground(Color.GRAY);
        txtEmail.setForeground(Color.GRAY);
        contentPanel.requestFocusInWindow();

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Vẽ ảnh phủ toàn bộ panel
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contentPanel = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        pnlDangNhap = new javax.swing.JPanel();
        lblQuayLai = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDangNhap = new javax.swing.JButton();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        contentPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.GridBagLayout());

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTieuDe.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        lblTieuDe.setText("XÁC NHẬN QUÊN MẬT KHẨU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        contentPanel.add(lblTieuDe, gridBagConstraints);

        txtTenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenDangNhap.setText("Tên đăng nhập");
        txtTenDangNhap.setPreferredSize(new java.awt.Dimension(300, 45));
        txtTenDangNhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenDangNhapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenDangNhapFocusLost(evt);
            }
        });
        txtTenDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenDangNhapMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTenDangNhapMouseExited(evt);
            }
        });
        txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDangNhapActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 310, 10, 0);
        contentPanel.add(txtTenDangNhap, gridBagConstraints);
        txtTenDangNhap.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tên đăng nhập");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setText("Nhập Email của bạn");
        txtEmail.setPreferredSize(new java.awt.Dimension(300, 45));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 310, 0, 0);
        contentPanel.add(txtEmail, gridBagConstraints);
        txtEmail.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập Email của bạn");

        pnlDangNhap.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        pnlDangNhap.setOpaque(false);
        pnlDangNhap.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 2, 5));

        lblQuayLai.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblQuayLai.setForeground(new java.awt.Color(0, 102, 255));
        lblQuayLai.setText("Quay lại");
        lblQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDangNhap.add(lblQuayLai);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(45, 100));
        pnlDangNhap.add(jPanel1);

        btnDangNhap.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Xác nhận");
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.setPreferredSize(new java.awt.Dimension(150, 45));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        pnlDangNhap.add(btnDangNhap);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contentPanel.add(pnlDangNhap, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(contentPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private static void setupLookAndFeel() {
        // Configure FlatLaf with white title bar
        System.setProperty("flatlaf.useWindowDecorations", "true");
        FlatLightLaf.setup();

        // Configure global title bar colors
        UIManager.put("TitlePane.background", Color.WHITE);
        UIManager.put("TitlePane.foreground", Color.BLACK);
        UIManager.put("TitlePane.inactiveBackground", Color.WHITE);
        UIManager.put("TitlePane.inactiveForeground", Color.GRAY);

        // Remove all shadow effects and gray colors
        UIManager.put("Component.focusWidth", 0);
        UIManager.put("Component.innerFocusWidth", 0);
        UIManager.put("Component.borderWidth", 0);
        UIManager.put("PopupMenu.borderWidth", 0);
        UIManager.put("ScrollPane.borderWidth", 0);
        UIManager.put("Panel.borderWidth", 0);

        // Remove default backgrounds that might cause gray colors
        UIManager.put("Panel.background", Color.WHITE);
        UIManager.put("ScrollPane.background", Color.WHITE);
        UIManager.put("Viewport.background", Color.WHITE);
    }
    javax.swing.JFrame parentFrame = (javax.swing.JFrame) SwingUtilities.getWindowAncestor(this);
    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        if (txtTenDangNhap.getText().length() == 0 || txtTenDangNhap.getText().equals("Tên đăng nhập")) {
            Notifications.getInstance().setJFrame(parentFrame);
            Notifications.getInstance().show(Notifications.Type.ERROR, "Vui lòng nhập tên đăng nhập!");
            txtTenDangNhap.requestFocus();
            return;
        }
        if (txtEmail.getText().length() == 0 || txtEmail.getText().equals("Nhập Email của bạn")) {
            Notifications.getInstance().setJFrame(parentFrame);
            Notifications.getInstance().show(Notifications.Type.ERROR, "Vui lòng nhập email để cấp lại mật khẩu!");
            txtEmail.requestFocus();
            return;
        }
        if (!new TaiKhoanDAO().isTenDangNhap(txtTenDangNhap.getText())) {
            Notifications.getInstance().setJFrame(parentFrame);
            Notifications.getInstance().show(Notifications.Type.ERROR, "Không tìm thấy tài khoản có tên đăng nhập là " + txtTenDangNhap.getText());
            txtTenDangNhap.requestFocus();
            return;
        }

        if (new EmailUtil().guiEmailCapPass(new NhanVienDAO().findById(txtTenDangNhap.getText()).get())) {
            Notifications.getInstance().setJFrame(parentFrame);
            Notifications.getInstance().show(Notifications.Type.SUCCESS, "Gửi thành công mật khẩu mới đến email " + txtEmail.getText() + '!');
        }
        this.setVisible(false);
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnDangNhapActionPerformed
    public void addPlayhoder(JTextField txt) {
        Font font = txt.getFont();
        font = font.deriveFont(Font.ITALIC);
        txt.setFont(font);
        txt.setForeground(Color.GRAY);
        txt.setBackground(Color.WHITE);
    }

    public void removePlayhoder(JTextField txt) {
        Font font = txt.getFont();
        font = font.deriveFont(Font.PLAIN);
        txt.setFont(font);
    }

    private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed

    }//GEN-LAST:event_txtTenDangNhapActionPerformed

    private void txtTenDangNhapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenDangNhapFocusGained
        if (txtTenDangNhap.getText().equals("Tên đăng nhập")) {
            txtTenDangNhap.setText("");
            txtTenDangNhap.setForeground(Color.BLACK);
            removePlayhoder(txtTenDangNhap);
        }

    }//GEN-LAST:event_txtTenDangNhapFocusGained

    private void txtTenDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenDangNhapMouseExited

    }//GEN-LAST:event_txtTenDangNhapMouseExited

    private void txtTenDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenDangNhapMouseClicked

    }//GEN-LAST:event_txtTenDangNhapMouseClicked

    private void txtTenDangNhapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenDangNhapFocusLost
        if (txtTenDangNhap.getText().length() == 0) {
            txtTenDangNhap.setText("Tên đăng nhập");
            addPlayhoder(txtTenDangNhap);
        }

    }//GEN-LAST:event_txtTenDangNhapFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.getText().equals("Nhập Email của bạn")) {
            txtEmail.setText("");
            txtEmail.setForeground(Color.BLACK);
            removePlayhoder(txtEmail);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().length() == 0) {
            txtEmail.setText("Nhập Email của bạn");
            addPlayhoder(txtEmail);
        }
    }//GEN-LAST:event_txtEmailFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuayLai;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlDangNhap;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
