/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.login;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author User
 */
public class LoginFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginFormPanel
     */
    public LoginFormPanel() {
        initComponents();
        btnDangNhap.putClientProperty("JButton.buttonType", "primary"); // không hoạt động nhưng mà đừng xóa :v
        
        txtTenDangNhap.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new com.formdev.flatlaf.extras.FlatSVGIcon("img/user_icon.svg"));
         txtMatKhau.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new com.formdev.flatlaf.extras.FlatSVGIcon("img/password_icon.svg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblFormContentPanel = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        pnlDangNhap = new javax.swing.JPanel();
        btnDangNhap = new javax.swing.JButton();
        lblQuenMatKhau = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        setLayout(new java.awt.GridBagLayout());

        lblFormContentPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        lblFormContentPanel.setLayout(new java.awt.GridBagLayout());

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTieuDe.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        lblTieuDe.setText("HỆ THỐNG QUẢN LÝ BÁN THUỐC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        lblFormContentPanel.add(lblTieuDe, gridBagConstraints);

        txtTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenDangNhap.setPreferredSize(new java.awt.Dimension(300, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 310, 10, 0);
        lblFormContentPanel.add(txtTenDangNhap, gridBagConstraints);
        txtTenDangNhap.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tên đăng nhập");

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMatKhau.setPreferredSize(new java.awt.Dimension(300, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 310, 10, 0);
        lblFormContentPanel.add(txtMatKhau, gridBagConstraints);
        txtMatKhau.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mật khẩu");

        pnlDangNhap.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        pnlDangNhap.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnDangNhap.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlDangNhap.add(btnDangNhap);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        lblFormContentPanel.add(pnlDangNhap, gridBagConstraints);

        lblQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(255, 51, 51));
        lblQuenMatKhau.setText("Quên mật khẩu");
        lblQuenMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        lblFormContentPanel.add(lblQuenMatKhau, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(lblFormContentPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JPanel lblFormContentPanel;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlDangNhap;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
