/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.login;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class LoginImagePanel extends javax.swing.JPanel {
    /**
     * Creates new form LoginImagePanel
     */

    /**
     * Creates new form LoginImagePanel
     */
    public LoginImagePanel() {
        initComponents();
 
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCenter = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        setLayout(new java.awt.BorderLayout());

        lblCenter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCenter;
    // End of variables declaration//GEN-END:variables
}
