/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.login;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.MediaTracker;
import javax.swing.ImageIcon;
import vn.edu.iuh.fit.iuhpharmacitymanagement.entity.NhanVien;
import vn.edu.iuh.fit.iuhpharmacitymanagement.session.SessionManager;

/**
 *
 * @author User
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setResizable(true); // Nên để true để người dùng có thể thu nhỏ lại cửa sổ

        // Set application icon
        try {
            java.net.URL iconUrl = getClass().getResource("/img/iuh.jpg");
            if (iconUrl != null) {
                ImageIcon iconIcon = new ImageIcon(iconUrl);
                Image icon = iconIcon.getImage();
                
                // Đảm bảo icon được load hoàn toàn trước khi set (tránh bất đồng bộ)
                MediaTracker tracker = new MediaTracker(this);
                tracker.addImage(icon, 0);
                try {
                    tracker.waitForID(0);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
                
                setIconImage(icon);
            }
        } catch (Exception e) {
            // Ignore if icon cannot be loaded
        }

        // Đảm bảo form login được focus khi frame hiển thị
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                // Frame đã mở, panel sẽ tự động focus thông qua ComponentListener
                loginFormPanel1.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginFormPanel1 = new vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.login.LoginFormPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1220, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(loginFormPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.login.LoginFormPanel loginFormPanel1;
    // End of variables declaration//GEN-END:variables
}
