/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.login;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class LoginImagePanel extends javax.swing.JPanel {
    /**
     * Creates new form LoginImagePanel
     */
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginImagePanel.class.getName());
    /**
     * Creates new form LoginImagePanel
     */
    public LoginImagePanel() {
        initComponents();
 
        new Thread(() -> {
            setImageToLabel(lblCenter, "/img/LoginImage.png");
        }).start();
    }

private void setImageToLabel(javax.swing.JLabel label, String imagePath) {
        try {
            java.net.URL imgURL = getClass().getResource(imagePath);
            System.out.println("Đường dẫn ảnh: " + imgURL);

            if (imgURL != null) {
                ImageIcon originalIcon = new ImageIcon(imgURL);
                Image scaledImage = originalIcon.getImage().getScaledInstance(
                        label.getWidth(),
                        label.getHeight(),
                        Image.SCALE_SMOOTH
                );
                label.setIcon(new ImageIcon(scaledImage));
            } else {
                logger.warning("Không tìm thấy ảnh ở đường dẫn: " + imagePath);
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Lỗi khi load hình ảnh", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCenter = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        setLayout(new java.awt.BorderLayout());

        lblCenter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCenter;
    // End of variables declaration//GEN-END:variables
}
