/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.login;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.Optional;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import raven.toast.Notifications;
import vn.edu.iuh.fit.iuhpharmacitymanagement.connectDB.ConnectDB;
import vn.edu.iuh.fit.iuhpharmacitymanagement.dao.TaiKhoanDAO;
import vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.form.MenuForm;
import vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.form.WelcomeFormNhanVien;

/**
 *
 * @author User
 */
public class LoginFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginFormPanel
     */
    private Image backgroundImage;

    public LoginFormPanel() {
        initComponents();
        backgroundImage = new ImageIcon(getClass().getResource("/img/LoginImage.png")).getImage();
        setOpaque(false); // Đảm bảo panel cho phép hiển thị ảnh nền
        contentPanel.setOpaque(true);
        contentPanel.setBackground(new java.awt.Color(255, 255, 255, 180));
        contentPanel.putClientProperty(FlatClientProperties.STYLE,
                "background:rgba(255,255,255,0.7); border:20, #FFFFFFAA;");
        contentPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1, true),
                javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));

        btnDangNhap.putClientProperty("JButton.buttonType", "primary"); // không hoạt động nhưng mà đừng xóa :v        
        txtTenDangNhap.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new com.formdev.flatlaf.extras.FlatSVGIcon("img/user_icon.svg"));
        txtMatKhau.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new com.formdev.flatlaf.extras.FlatSVGIcon("img/password_icon.svg"));
        txtTenDangNhap.setText("Tên đăng nhập");
        txtMatKhau.setText("Nhập mật khẩu");
        //mặt focus vào pnl đẻ txt k mất playhoder
        contentPanel.setFocusable(true);
        contentPanel.requestFocusInWindow();
        addPlayhoder(txtTenDangNhap);
        addPlayhoder(txtMatKhau);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Vẽ ảnh phủ toàn bộ panel
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contentPanel = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        pnlDangNhap = new javax.swing.JPanel();
        btnDangNhap = new javax.swing.JButton();
        lblQuenMatKhau = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        contentPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.GridBagLayout());

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTieuDe.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        lblTieuDe.setText("HỆ THỐNG QUẢN LÝ BÁN THUỐC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        contentPanel.add(lblTieuDe, gridBagConstraints);

        txtTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenDangNhap.setPreferredSize(new java.awt.Dimension(300, 45));
        txtTenDangNhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenDangNhapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenDangNhapFocusLost(evt);
            }
        });
        txtTenDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenDangNhapMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTenDangNhapMouseExited(evt);
            }
        });
        txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDangNhapActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 310, 10, 0);
        contentPanel.add(txtTenDangNhap, gridBagConstraints);
        txtTenDangNhap.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tên đăng nhập");

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMatKhau.setPreferredSize(new java.awt.Dimension(300, 45));
        txtMatKhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMatKhauFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatKhauFocusLost(evt);
            }
        });
        txtMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMatKhauMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 310, 10, 0);
        contentPanel.add(txtMatKhau, gridBagConstraints);
        txtMatKhau.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mật khẩu");

        pnlDangNhap.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.success.borderColor"));
        pnlDangNhap.setOpaque(false);
        pnlDangNhap.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnDangNhap.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.setPreferredSize(new java.awt.Dimension(150, 45));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        pnlDangNhap.add(btnDangNhap);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contentPanel.add(pnlDangNhap, gridBagConstraints);

        lblQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(255, 51, 51));
        lblQuenMatKhau.setText("Quên mật khẩu");
        lblQuenMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        contentPanel.add(lblQuenMatKhau, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(contentPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    TaiKhoanDAO tkDao = new TaiKhoanDAO();

    private static void setupLookAndFeel() {
        // Configure FlatLaf with white title bar
        System.setProperty("flatlaf.useWindowDecorations", "true");
        FlatLightLaf.setup();

        // Configure global title bar colors
        UIManager.put("TitlePane.background", Color.WHITE);
        UIManager.put("TitlePane.foreground", Color.BLACK);
        UIManager.put("TitlePane.inactiveBackground", Color.WHITE);
        UIManager.put("TitlePane.inactiveForeground", Color.GRAY);

        // Remove all shadow effects and gray colors
        UIManager.put("Component.focusWidth", 0);
        UIManager.put("Component.innerFocusWidth", 0);
        UIManager.put("Component.borderWidth", 0);
        UIManager.put("PopupMenu.borderWidth", 0);
        UIManager.put("ScrollPane.borderWidth", 0);
        UIManager.put("Panel.borderWidth", 0);

        // Remove default backgrounds that might cause gray colors
        UIManager.put("Panel.background", Color.WHITE);
        UIManager.put("ScrollPane.background", Color.WHITE);
        UIManager.put("Viewport.background", Color.WHITE);
    }
    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        System.out.println("đã nhấn");
        try {
            ConnectDB.getConnection();
        } catch (SQLException ex) {
            System.getLogger(LoginFormPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }                
         if(txtTenDangNhap.getText().trim().isEmpty() || txtTenDangNhap.getText().trim().length() == 0){
          Notifications.getInstance().setJFrame(new LoginFrame());
            Notifications.getInstance().show(
                    Notifications.Type.ERROR,
                    Notifications.Location.TOP_CENTER,
                    "Hãy nhập tên đăng nhập!"
            );            
             System.out.println("áđâsdâsdâsda");
            txtTenDangNhap.requestFocus();
            return;
         }
         if(txtMatKhau.getText().trim().isEmpty() || txtMatKhau.getText().trim().length() ==0){
              Notifications.getInstance().setJFrame(new LoginFrame());
            Notifications.getInstance().show(
                    Notifications.Type.ERROR,
                    Notifications.Location.TOP_CENTER,
                    "Hãy nhập mật đăng nhập!"
            );            
            txtMatKhau.requestFocus();
            return;
         }
          Optional<String> optVaiTro = tkDao.tonTaiTaiKhoanKhiLogin(txtTenDangNhap.getText(), txtMatKhau.getText());  
          if (optVaiTro.isEmpty()) {           
            Notifications.getInstance().setJFrame(new LoginFrame());
            Notifications.getInstance().show(
                    Notifications.Type.ERROR,
                    Notifications.Location.TOP_CENTER,
                    "Sai tên đăng nhập hoặc mật khẩu hãy nhập lại!"
            );
            txtTenDangNhap.requestFocus();
            return;
        }
        if (optVaiTro.get().equalsIgnoreCase("Quản lý")  ) {
            SwingUtilities.invokeLater(() -> {
                Notifications.getInstance().setJFrame(new LoginFrame());
                    Notifications.getInstance().show(Notifications.Type.INFO,
                            Notifications.Location.TOP_CENTER,
                            "Đăng nhập thành công! xin chào Quản lý");
                try {
                    setupLookAndFeel();                    
                    new MenuForm().setVisible(true);
                    this.setVisible(false);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });

        } else if (optVaiTro.get().equalsIgnoreCase("Nhân viên")) {
            // Đăng nhập cho Nhân viên
            Notifications.getInstance().setJFrame(new LoginFrame());
            Notifications.getInstance().show(
                    Notifications.Type.SUCCESS,
                    Notifications.Location.TOP_CENTER,
                    "Đăng nhập thành công! Xin chào Nhân viên!"
            );
           //để xử lý sau
           this.setVisible(false);
        }          

    }//GEN-LAST:event_btnDangNhapActionPerformed
    public void addPlayhoder(JTextField txt) {
        Font font = txt.getFont();
        font = font.deriveFont(Font.ITALIC);
        txt.setFont(font);
        txt.setBackground(Color.WHITE);
    }

    public void removePlayhoder(JTextField txt) {
        Font font = txt.getFont();
        font = font.deriveFont(Font.PLAIN | Font.BOLD);
        txt.setFont(font);
    }
    private void txtMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMatKhauMouseClicked
        // txtMatKhau.
    }//GEN-LAST:event_txtMatKhauMouseClicked

    private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhapActionPerformed

    private void txtTenDangNhapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenDangNhapFocusGained
        if (txtTenDangNhap.getText().equals("Tên đăng nhập")) {
            txtTenDangNhap.setText("");
            txtTenDangNhap.requestFocus();
            removePlayhoder(txtTenDangNhap);
        }
    }//GEN-LAST:event_txtTenDangNhapFocusGained

    private void txtTenDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenDangNhapMouseExited
//        if(txtTenDangNhap.getText().equals("")){
//            txtTenDangNhap.setText("Tên đăng nhập");                        
//            txtMatKhau.requestFocus();           
//            removePlayhoder(txtMatKhau);
//        }
    }//GEN-LAST:event_txtTenDangNhapMouseExited

    private void txtTenDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenDangNhapMouseClicked

    }//GEN-LAST:event_txtTenDangNhapMouseClicked

    private void txtMatKhauFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatKhauFocusGained
        if (txtMatKhau.getText().equals("Nhập mật khẩu")) {
            txtMatKhau.setText("");
            removePlayhoder(txtMatKhau);
        }
    }//GEN-LAST:event_txtMatKhauFocusGained

    private void txtTenDangNhapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenDangNhapFocusLost
        if (txtTenDangNhap.getText().length() == 0) {
            addPlayhoder(txtTenDangNhap);
            txtTenDangNhap.setText("Tên đăng nhập");
        }
    }//GEN-LAST:event_txtTenDangNhapFocusLost

    private void txtMatKhauFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatKhauFocusLost
        if (txtMatKhau.getText().length() == 0) {
            addPlayhoder(txtMatKhau);
            txtMatKhau.setText("Nhập mật khẩu");
        }
    }//GEN-LAST:event_txtMatKhauFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlDangNhap;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
