/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.form;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author PhamTra
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    public static MainForm mainForm;

    public MenuForm() {
        initComponents();

        // Cấu hình thanh tiêu đề màu trắng
        getRootPane().putClientProperty("JRootPane.titleBarBackground", java.awt.Color.WHITE);
        getRootPane().putClientProperty("JRootPane.titleBarForeground", java.awt.Color.BLACK);

        // Đặt màu nền trắng cho toàn bộ cửa sổ và loại bỏ mọi màu xám
        getContentPane().setBackground(java.awt.Color.WHITE);
        setBackground(java.awt.Color.WHITE);

        // Loại bỏ mọi border có thể gây ra màu xám
        getRootPane().setBorder(null);

        // Đặt tiêu đề cho ứng dụng
        setTitle("IUH Pharmacity Management");

        mainForm = new MainForm();
        setContentPane(mainForm);

        // Thiết lập cửa sổ hiển thị giữa màn hình
        setLocationRelativeTo(null);

        // Thiết lập kích thước cửa sổ
        setSize(1200, 800);

        // Đảm bảo cửa sổ hiển thị giữa màn hình sau khi set size
        setLocationRelativeTo(null);
    }

    /**
     * Entry point chính của ứng dụng - tích hợp từ MainApplication
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            try {
                // Cấu hình FlatLaf với thanh tiêu đề màu trắng
                System.setProperty("flatlaf.useWindowDecorations", "true");

                // Thiết lập Look and Feel
                FlatLightLaf.setup();

                // Cấu hình màu thanh tiêu đề toàn cục
                UIManager.put("TitlePane.background", java.awt.Color.WHITE);
                UIManager.put("TitlePane.foreground", java.awt.Color.BLACK);
                UIManager.put("TitlePane.inactiveBackground", java.awt.Color.WHITE);
                UIManager.put("TitlePane.inactiveForeground", java.awt.Color.GRAY);

                // Loại bỏ tất cả shadow effects và màu xám
                UIManager.put("Component.focusWidth", 0);
                UIManager.put("Component.innerFocusWidth", 0);
                UIManager.put("Component.borderWidth", 0);
                UIManager.put("PopupMenu.borderWidth", 0);
                UIManager.put("ScrollPane.borderWidth", 0);
                UIManager.put("Panel.borderWidth", 0);

                // Loại bỏ background mặc định có thể gây màu xám
                UIManager.put("Panel.background", java.awt.Color.WHITE);
                UIManager.put("ScrollPane.background", java.awt.Color.WHITE);
                UIManager.put("Viewport.background", java.awt.Color.WHITE);

                // Khởi tạo ứng dụng
                new MenuForm().setVisible(true);

            } catch (Exception e) {
                e.printStackTrace();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Cấu hình thanh tiêu đề trước khi tạo layout
        getRootPane().putClientProperty("JRootPane.titleBarBackground", java.awt.Color.WHITE);
        getRootPane().putClientProperty("JRootPane.titleBarForeground", java.awt.Color.BLACK);

        // Đặt background màu trắng cho frame và loại bỏ mọi màu xám
        setBackground(java.awt.Color.WHITE);

        // Đặt màu nền trắng cho layout
        getContentPane().setBackground(java.awt.Color.WHITE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
