/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.quanly.dashboard;

import raven.toast.Notifications;
import vn.edu.iuh.fit.iuhpharmacitymanagement.bus.ChiTietDonHangBUS;
import vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.barchart.Chart;
import vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.barchart.ModelChart;
import vn.edu.iuh.fit.iuhpharmacitymanagement.constant.LoaiSanPham;
import vn.edu.iuh.fit.iuhpharmacitymanagement.dao.ChiTietDonHangDAO.ProductSalesSummary;

import javax.swing.DefaultComboBoxModel;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author PhamTra
 */
public class Panel_XuHuongMuaHang extends javax.swing.JPanel {
    
    private static final int TOP_PRODUCT_LIMIT = 5;
    private static final int MAX_PRODUCT_NAME_LENGTH = 15;

    private final ChiTietDonHangBUS chiTietDonHangBUS;
    private Chart chart;
    private final Map<String, LoaiSanPham> productTypeOptions = new LinkedHashMap<>();

    public Panel_XuHuongMuaHang() {
        chiTietDonHangBUS = new ChiTietDonHangBUS();
        initChart();
        initComponents();
        initProductTypeFilter();
        initSimpleUI();
    }
    
    private void initChart() {
        chart = new Chart();
        chart.addLegend("Số lượng bán", new Color(245, 189, 135));
    }
    
    private void initSimpleUI() {
        jDateFrom.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant()));
        jDateTo.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant()));
        lbdt.setVisible(false);
        lbt5.setVisible(false);
        lbtl.setVisible(false);
    }

    private void initProductTypeFilter() {
        productTypeOptions.clear();
        productTypeOptions.put("Tất cả", null);
        for (LoaiSanPham type : LoaiSanPham.values()) {
            productTypeOptions.put(toDisplayName(type), type);
        }

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(
                productTypeOptions.keySet().toArray(new String[0])
        );
        comboProductType.setModel(model);
        comboProductType.setSelectedIndex(0);
    }

    private String toDisplayName(LoaiSanPham type) {
        switch (type) {
            case THUOC:
                return "Thuốc";
            case VAT_TU_Y_TE:
                return "Vật tư y tế";
            case THUC_PHAM_CHUC_NANG:
                return "Thực phẩm chức năng";
            case CHAM_SOC_TRE_EM:
                return "Chăm sóc trẻ em";
            case THIET_BI_Y_TE:
                return "Thiết bị y tế";
            default:
                return type.name();
        }
    }

    private LoaiSanPham getSelectedProductType() {
        Object selected = comboProductType.getSelectedItem();
        if (selected == null) {
            return null;
        }
        return productTypeOptions.getOrDefault(selected.toString(), null);
    }

    private String formatProductLabel(String name, String fallback) {
        String value = (name == null || name.isBlank()) ? fallback : name.trim();
        if (value.length() > MAX_PRODUCT_NAME_LENGTH) {
            return value.substring(0, MAX_PRODUCT_NAME_LENGTH) + "...";
        }
        return value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblXuHuong = new javax.swing.JLabel();
        lbdt = new javax.swing.JLabel();
        lbt5 = new javax.swing.JLabel();
        lbtl = new javax.swing.JLabel();
        pnContent = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        lblChartProduct = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jDateTo = new com.toedter.calendar.JDateChooser();
        jDateFrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboProductType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 6, 0, 6, new java.awt.Color(255, 255, 255)));
        jPanel1.setMinimumSize(new java.awt.Dimension(1130, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1130, 800));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 6));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1118, 430));

        lblXuHuong.setBackground(new java.awt.Color(255, 255, 255));
        lblXuHuong.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblXuHuong.setText("XU HƯỚNG MUA HÀNG");
        lblXuHuong.setPreferredSize(new java.awt.Dimension(37, 30));

        lbdt.setBackground(new java.awt.Color(255, 255, 255));
        lbdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbdt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbdt.setText("Doanh Thu Theo Loại");

        lbt5.setBackground(new java.awt.Color(255, 255, 255));
        lbt5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbt5.setText("Xu Hướng Mua");

        lbtl.setBackground(new java.awt.Color(255, 255, 255));
        lbtl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbtl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtl.setText("Số Lượng Theo Loại");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblXuHuong, javax.swing.GroupLayout.PREFERRED_SIZE, 1118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(150, 150, 150)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbtl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(150, 150, 150)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbt5, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))))
                .addGap(162, 162, 162))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblXuHuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbt5)
                    .addComponent(lbtl))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pnContent.setBackground(new java.awt.Color(255, 255, 255));
        pnContent.setLayout(new java.awt.BorderLayout(0, 20));

        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setPreferredSize(new java.awt.Dimension(1188, 40));
        jPanel16.setLayout(new java.awt.BorderLayout());

        lblChartProduct.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblChartProduct.setText("TOP 5 SẢN PHẨM BÁN CHẠY");
        lblChartProduct.setMaximumSize(new java.awt.Dimension(600, 40));
        lblChartProduct.setMinimumSize(new java.awt.Dimension(600, 40));
        lblChartProduct.setPreferredSize(new java.awt.Dimension(600, 40));
        jPanel16.add(lblChartProduct, java.awt.BorderLayout.WEST);

        jPanel14.add(jPanel16, java.awt.BorderLayout.PAGE_START);
        
        // Thêm chart thực sự
        jPanel14.add(chart, java.awt.BorderLayout.CENTER);

        pnContent.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnContent, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(232, 232, 232)));
        jPanel5.setPreferredSize(new java.awt.Dimension(590, 100));

        btnSearch.setBackground(new java.awt.Color(115, 165, 71));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Tìm kiếm");
        btnSearch.setMaximumSize(new java.awt.Dimension(150, 40));
        btnSearch.setMinimumSize(new java.awt.Dimension(150, 40));
        btnSearch.setPreferredSize(new java.awt.Dimension(150, 40));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jDateTo.setBackground(new java.awt.Color(255, 255, 255));
        jDateTo.setDateFormatString("dd/MM/yyyy");
        jDateTo.setFocusable(false);
        jDateTo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jDateTo.setPreferredSize(new java.awt.Dimension(100, 22));

        jDateFrom.setBackground(new java.awt.Color(255, 255, 255));
        jDateFrom.setDateFormatString("dd/MM/yyyy");
        jDateFrom.setFocusable(false);
        jDateFrom.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jDateFrom.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("-->");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Ngày bắt đầu");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Ngày kết thúc");

        comboProductType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Loại sản phẩm");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboProductType, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jDateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(jDateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel5, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (jDateFrom.getDate() == null || jDateTo.getDate() == null) {
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER, "Vui lòng chọn ngày bắt đầu và ngày kết thúc");
            return;
        }
        
        LocalDate dateFrom = jDateFrom.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dateTo = jDateTo.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        if (dateFrom.isAfter(dateTo)) {
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER, "Ngày bắt đầu phải trước ngày kết thúc");
            return;
        }
        
        loadTopProducts(dateFrom, dateTo);
        Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, "Đã tải dữ liệu xu hướng mua hàng");
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void loadTopProducts(LocalDate dateFrom, LocalDate dateTo) {
        chart.clear();

        LoaiSanPham selectedType = getSelectedProductType();
        List<ProductSalesSummary> topProducts = chiTietDonHangBUS.layTopSanPhamBanChay(
                dateFrom,
                dateTo,
                selectedType,
                TOP_PRODUCT_LIMIT
        );

        for (ProductSalesSummary summary : topProducts) {
            String label = formatProductLabel(summary.getProductName(), summary.getProductId());
            chart.addData(new ModelChart(label, new double[]{summary.getTotalQuantity()}));
        }

        chart.start();

        if (topProducts.isEmpty()) {
            lblChartProduct.setText("KHÔNG CÓ SẢN PHẨM NÀO TRONG KHOẢNG THỜI GIAN NÀY");
        } else {
            lblChartProduct.setText("TOP " + topProducts.size() + " SẢN PHẨM BÁN CHẠY");
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboProductType;
    private com.toedter.calendar.JDateChooser jDateFrom;
    private com.toedter.calendar.JDateChooser jDateTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbdt;
    private javax.swing.JLabel lblChartProduct;
    private javax.swing.JLabel lblXuHuong;
    private javax.swing.JLabel lbt5;
    private javax.swing.JLabel lbtl;
    private javax.swing.JPanel pnContent;
    // End of variables declaration//GEN-END:variables
}
