/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.iuh.fit.iuhpharmacitymanagement.gui.application.quanly.dashboard;

/**
 *
 * @author PhamTra
 */
public class Panel_ThongKeTheoThoiGian extends javax.swing.JPanel {

    /**
     * Creates new form PnStatsByTime
     */
    public Panel_ThongKeTheoThoiGian() {
        initComponents();
        inItTab();
    }

    private void inItTab() {
        tabbedStatTime.add("Theo ngày", new Panel_ThongKeTheoNgay());
        tabbedStatTime.add("Theo tháng", new Panel_ThongKeTheoThang());
        tabbedStatTime.add("Theo năm", new Panel_ThongKeTheoNam());

        tabbedStatTime.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedStatTime = new javax.swing.JTabbedPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        tabbedStatTime.setBackground(new java.awt.Color(255, 255, 255));
        add(tabbedStatTime);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedStatTime;
    // End of variables declaration//GEN-END:variables
}
